### ISSUE TITLE
AttributeError: 'URL' object has no attribute 'host_port_subcomponent'. Did you mean: 'host_subcomponent'?

### ISSUE THREAD

**Issue by Geremia** [fafhrd91/aiohttp#10286]
### Describe the bug

I get an "`AttributeError: 'URL' object has no attribute 'host_port_subcomponent'. Did you mean: 'host_subcomponent'?`" when trying to start [Electrum 4.5.8](https://github.com/spesmilo/electrum/issues/9389).

### To Reproduce

This occurs upon starting Electrum.

### Expected behavior

It seems the `URL` object should have a `host_port_subcomponent`.

### Logs/tracebacks

```python-traceback
$ electrum 
  0.85 | E | __main__ | 
Traceback (most recent call last):
  File "/usr/bin/electrum", line 444, in main
    handle_cmd(
  File "/usr/bin/electrum", line 457, in handle_cmd
    fd = daemon.get_file_descriptor(config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/electrum/daemon.py", line 103, in get_file_descriptor
    request(config, 'ping')
  File "/usr/lib/python3.12/site-packages/electrum/daemon.py", line 147, in request
    return fut.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/site-packages/electrum/daemon.py", line 144, in request_coroutine
    return await c.request(endpoint, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/electrum/util.py", line 1973, in request
    async with self.session.post(self.url, data=data) as resp:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/aiohttp/client.py", line 1425, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/aiohttp/client.py", line 675, in _request
    req = self._request_class(
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/aiohttp/client_reqrep.py", line 351, in __init__
    self.update_headers(headers)
  File "/usr/lib64/python3.12/site-packages/aiohttp/client_reqrep.py", line 460, in update_headers
    host = self.url.host_port_subcomponent
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Python Version

```console
$ python --version
Python 3.12.8
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.11.11
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache-2.0
Location: /usr/lib64/python3.12/site-packages
Requires: aiohappyeyeballs, aiosignal, attrs, frozenlist, multidict, propcache, yarl
Required-by: aiohttp_socks, Electrum
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib64/python3.12/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### propcache Version

```console
$ python -m pip show propcache
Name: propcache
Version: 0.2.1
Summary: Accelerated property cache
Home-page: https://github.com/aio-libs/propcache
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /usr/lib64/python3.12/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.15.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /usr/lib64/python3.12/site-packages
Requires: idna, multidict, propcache
Required-by: aiohttp
```

### OS

slackware64-current
Linux 6.12.6

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Geremia** [comment]
Upgrading yarl-1.15.2 → yarl-1.18.3 fixed this issue.

**Comment by Dreamsorcerer** [comment]
1.15 isn't supported, so pip should have done that for you...
https://github.com/aio-libs/aiohttp/blob/b103bbca6b753e5b5357367cbaed10c7eade5a44/setup.cfg#L61

**Comment by Geremia** [comment]
@Dreamsorcerer I'm building them myself with [SlackBuilds](https://slackbuilds.org/), not using `pip`; that's why.

**Comment by webknjaz** [comment]
@Geremia you still have to respect the deps declarations in the metadata.
