### ISSUE TITLE
Adding middleware to server is changing the downstream request type

### ISSUE THREAD

**Issue by kabua** [fafhrd91/aiohttp#6015]
### Describe the bug

Without adding middleware, the request param to my handler is of type `<class 'aiohttp.web_request.Request'>`, which has a `query` attribute. However, if I add a middleware handler (derived from the [docs](https://docs.aiohttp.org/en/latest/web_advanced.html#aiohttp-web-middlewares)) the request param is now of type `<class 'aiohttp.web_app.Application'>`, which does not have a `query` attribute and thus my code is throwing an error.

### To Reproduce

Here's a simple example of the issue:
```
import json

from aiohttp import web
from aiohttp.web_request import Request

routes = web.RouteTableDef()


async def exception_middleware(request, handler):
    try:
        print(type(request))
        response = await handler(request)
    except Exception as e:
        response = web.json_response(e, status=400)
    return response

@routes.post('/user')
async def new_user(request: Request) -> web.Response:
        print(type(request))
        user = request.query['name']
        print("Creating new user with name: ", user)

        response_obj = {'status': 'success'}
        return web.json_response(response_obj)

app = web.Application(middlewares=[exception_middleware])
#app = web.Application()
app.add_routes(routes)
web.run_app(app)
```

Request:
```
Post http://localhost:8080/user?name=Testing
```

Actual output:
```
<class 'aiohttp.web_app.Application'>
<class 'aiohttp.web_app.Application'>
Error handling request
Traceback (most recent call last):
  File "C:\scratch.py", line 12, in exception_middleware
    response = await handler(request)
  File "C:\scratch.py", line 20, in new_user
    user = request.query['name']
AttributeError: 'Application' object has no attribute 'query'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\site-packages\aiohttp\web_app.py", line 497, in _handle
    handler = await m(app, handler)  # type: ignore
  File "C:\Users\tristen\AppData\Roaming\JetBrains\PyCharmCE2021.2\scratches\scratch.py", line 14, in exception_middleware
    response = web.json_response(e, status=400)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\site-packages\aiohttp\web_response.py", line 773, in json_response
    text = dumps(data)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
```

### Expected behavior

Here's what I was expecting:
```import json

from aiohttp import web
from aiohttp.web_request import Request

routes = web.RouteTableDef()


async def exception_middleware(request, handler):
    try:
        print(type(request))
        response = await handler(request)
    except Exception as e:
        response = web.json_response(e, status=400)
    return response

@routes.post('/user')
async def new_user(request: Request) -> web.Response:
        print(type(request))
        user = request.query['name']
        print("Creating new user with name: ", user)

        response_obj = {'status': 'success'}
        return web.json_response(response_obj)

#app = web.Application(middlewares=[exception_middleware])
app = web.Application()
app.add_routes(routes)
web.run_app(app)
```

Request:
```
Post http://localhost:8080/user?name=Testing
```

Expected output:
```
<class 'aiohttp.web_request.Request'>
Creating new user with name:  Testing
```

### Logs/tracebacks

```python-traceback
<class 'aiohttp.web_app.Application'>
<class 'aiohttp.web_app.Application'>
Error handling request
Traceback (most recent call last):
  File "C:\scratch.py", line 12, in exception_middleware
    response = await handler(request)
  File "C:\scratch.py", line 20, in new_user
    user = request.query['name']
AttributeError: 'Application' object has no attribute 'query'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\site-packages\aiohttp\web_app.py", line 497, in _handle
    handler = await m(app, handler)  # type: ignore
  File "C:\Users\tristen\AppData\Roaming\JetBrains\PyCharmCE2021.2\scratches\scratch.py", line 14, in exception_middleware
    response = web.json_response(e, status=400)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\site-packages\aiohttp\web_response.py", line 773, in json_response
    text = dumps(data)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\ProgramData\Anaconda3\envs\DLAcquire\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
```

### Python Version

```console
$ python --version
Python 3.9.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: c:\programdata\anaconda3\envs\dlacquire\lib\site-packages
Requires: async-timeout, multidict, chardet, attrs, typing-extensions, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\programdata\anaconda3\envs\dlacquire\lib\site-packages
Requires:
Required-by: yarl, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\programdata\anaconda3\envs\dlacquire\lib\site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Windows 10 Pro 
Version	10.0.19042 Build 19042

### Related component

Server

### Additional context

Is a simple scratch file, written and running in PyCharm.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by kabua** [comment]
**Fixed**
It appears that 4.0 hasn't been released yet and therefore, I need to still use @middleware

**Comment by kabua** [comment]
**Fixed**
It appears that 4.0 hasn't been released yet and therefore, I need to still use @middleware
