### ISSUE TITLE
URL raises InvalidURL even though the URL is valid

### ISSUE THREAD

**Issue by Lagicrus** [fafhrd91/aiohttp#6017]
### Describe the bug

URL is marked as invalid, even though the validators package and browsing to it, work.

### To Reproduce

1. Use AIOHTTP to create a ClientSession
2. Do a session.get on `https://2w8ov.2h4zh2chks.com/t/8f0d93c8664e/d6a8636e-1ae2-11ec-8a5c-55cdaa16b17d?fallback=1`
3. Watch it fail

### Expected behavior

To be able to fetch the specified URL

### Logs/tracebacks

<details><summary>Traceback</summary>

```python-traceback
Traceback (most recent call last):
   File "/app/spoopy/websocket.py", line 49, in ws_spoopy
     = await get_check_website(url, request.app.session, request.app.db, request.app.fish)
   File "/app/api/tool_check_website_wrapper.py", line 15, in get_check_website
     async with session.get(url, allow_redirects=False, headers={"User-Agent": get_random_user_agent()}) as resp:
   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
     self._resp = await self._coro
   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 492, in _request
     req = self._request_class(
   File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
     self.update_host(url)
   File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
     raise InvalidURL(URL)
```

</details>

### Python Version

```console
$ python --version
Python 3.8.11
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.8/site-packages
Requires: yarl, multidict, async-timeout, chardet, typing-extensions, attrs
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.8/site-packages
Requires:
Required-by: yarl, sanic, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl (this also broke on 1.6.3)
Name: yarl
Version: 1.6.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.8/site-packages
Requires: multidict, idna
Required-by: aiohttp
```

### OS

Docker Compose container

### Related component

Client

### Additional context

I have also tried doing the same as the internal yarl check, but this seems to succeed which is where I am confused.

```python
Python 3.8.11 (default, Aug 17 2021, 15:56:41)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yarl
>>> yarl.URL("https://2w8ov.2h4zh2chks.com/t/8f0d93c8664e/d6a8636e-1ae2-11ec-8a5c-55cdaa16b17d?fallback=1").raw_host
'2w8ov.2h4zh2chks.com'
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Lagicrus** [comment]
Update, this is also now somehow affecting google?
`aiohttp.client_exceptions.InvalidURL: 'https://google.com'`

**Comment by Dreamsorcerer** [comment]
Actual, reproducible code would make it a lot faster to help you.

This works without any issues for me:
```
import asyncio

from aiohttp import ClientSession

url = "https://2w8ov.2h4zh2chks.com/t/8f0d93c8664e/d6a8636e-1ae2-11ec-8a5c-55cdaa16b17d?fallback=1"

async def main():
    async with ClientSession() as session:
        async with session.get(url) as resp:
            print(await resp.text())

asyncio.run(main())
```

Although the `fallback=1` should really be passed separately like:
`session.get(url, params={"fallback": "1"})`

**Comment by Lagicrus** [comment]
I don't control the URL otherwise I would have done that, thanks for pointing that out however
Turned out the issue was the extra '
When it errored I thought it was intended as part of the error message, to signify where the error was. Turns out that was "part" of the URL
That was a fun confusion
