### ISSUE TITLE
AttributeError: module 'aiohttp' has no attribute 'Signal'

### ISSUE THREAD

**Issue by NaokoReeves-BO** [fafhrd91/aiohttp#6197]
### Describe the bug

```
Python 3.7.10 (default, May  5 2021, 13:11:39) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aiohttp import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiohttp' has no attribute 'Signal'
```

### To Reproduce

```
Python 3.7.10 (default, May  5 2021, 13:11:39) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aiohttp import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiohttp' has no attribute 'Signal'
```

### Expected behavior

No error. 

### Logs/tracebacks

```python-traceback
Python 3.7.10 (default, May  5 2021, 13:11:39) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aiohttp import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiohttp' has no attribute 'Signal'
```

### Python Version

```console
$ python --version
3.7.10
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /Users/naoko.reeves/.pyenv/versions/3.7.10/envs/mdl-pipelines-3.7.10/lib/python3.7/site-packages
Requires: aiosignal, async-timeout, asynctest, attrs, charset-normalizer, frozenlist, multidict, typing-extensions, yarl
Required-by: pytest-aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/naoko.reeves/.pyenv/versions/3.7.10/envs/mdl-pipelines-3.7.10/lib/python3.7/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.0
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/naoko.reeves/.pyenv/versions/3.7.10/envs/mdl-pipelines-3.7.10/lib/python3.7/site-packages
Requires: idna, multidict, typing-extensions
Required-by: aiohttp
```

### OS

macOSX

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
How is this not caught by flake8...?
