### ISSUE TITLE
asyncio-timeout==4.0.1 breaks aiohttp==2.3.10

### ISSUE THREAD

**Issue by nsurleraux-railnova** [fafhrd91/aiohttp#6320]
### Describe the bug

When installing `aiohttp==2.3.10`, it now ships `async-timeout==4.0.1` which causes an error at import (see Logs below).

### To Reproduce

1. `pip install aiohttp==2.3.10`
2. `import aiohttp`

### Expected behavior

It should ship `async-timeout==3.0.1` or any version compatible.

### Logs/tracebacks

```python-traceback
-------------------------------------------------------------------------------------------------------------
|   timestamp   |                                          message                                          |
|---------------|-------------------------------------------------------------------------------------------|
| 1637160395727 | Traceback (most recent call last):                                                        |
| 1637160395727 |   File "webui/webui.py", line 9, in <module>                                              |
| 1637160395727 |     import aiohttp                                                                        |
| 1637160395727 |   File "/webui/ve/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>   |
| 1637160395727 |     from .client import *  # noqa                                                         |
| 1637160395727 |   File "/webui/ve/lib/python3.7/site-packages/aiohttp/client.py", line 15, in <module>    |
| 1637160395727 |     from . import connector as connector_mod                                              |
| 1637160395727 |   File "/webui/ve/lib/python3.7/site-packages/aiohttp/connector.py", line 12, in <module> |
| 1637160395727 |     from . import hdrs, helpers                                                           |
| 1637160395727 |   File "/webui/ve/lib/python3.7/site-packages/aiohttp/helpers.py", line 742, in <module>  |
| 1637160395727 |     class CeilTimeout(Timeout):                                                           |
| 1637160395727 | TypeError: function() argument 1 must be code, not str                                    |
-------------------------------------------------------------------------------------------------------------
```

### Python Version

```console
$ python --version
Python 3.7.11
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 2.3.10
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp/
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /webui/ve/lib/python3.7/site-packages
Requires: async-timeout, chardet, idna-ssl, multidict, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /webui/ve/lib/python3.7/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /webui/ve/lib/python3.7/site-packages
Requires: idna, multidict, typing-extensions
Required-by: aiohttp
```

### OS

Debian 9 in Docker

### Related component

Client

### Additional context

```
$ python -m pip show async-timeout
Name: async-timeout
Version: 4.0.1
Summary: Timeout context manager for asyncio programs
Home-page: https://github.com/aio-libs/async-timeout
Author: Andrew Svetlov <andrew.svetlov@gmail.com>
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /webui/ve/lib/python3.7/site-packages
Requires: typing-extensions
Required-by: aiohttp
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I'm guessing there was no upper bound on the requirements in that old version. But, that release that is almost 4 years old... There are no branches or anything still around for those releases, so probably no easy way to even change the packaging information.

I'm sure there are also security issues etc. with such an old release, so I'd strongly suggest upgrading to a 3.8 release.

**Comment by webknjaz** [comment]
It's not a bug. That version of aiohttp is EOL, it's not supported, nor will it get any updates. Ever.

On another note, here's how to manage your application dependencies properly:
- https://hynek.me/articles/semver-will-not-save-you/#taking-responsibility
- https://hynek.me/articles/python-app-deps-2018/#pip-tools--everything-old-is-new-again

Do this, and your updates will be more predictable and your deployment will become more reliable/reproducible.

**Comment by Salamandar** [comment]
I've this issue with aiohttp 3.7.4 installed as a dependency of heisenbridge (https://github.com/hifi/heisenbridge)  (requirement is aiohttp<3.8,>=3.6). Manually upgrade it to 3.8.1 fixes the issue.

**Comment by asvetlov** [comment]
I'm curious what did you use for 3.7.4 installation?
Maybe outdated `pip`?
aiohttp 3.7.4 has `async-timeout<4.0,>=3.0` requirement, it doesn't allow installing async-timeout==4.x

**Comment by Salamandar** [comment]
Actually I didn't check what async-timeout version I had :( But yes, I used pip to install heisenbridge and its dependencies.

**Comment by Dreamsorcerer** [comment]
If I pip install that, it installs 3.0.1 as expected

> Successfully installed aiohttp-3.7.4.post0 async-timeout-3.0.1 heisenbridge-1.7.1 importlib-resources-5.4.0 irc-19.0.1 jaraco.classes-3.2.1 jaraco.collections-3.4.0 jaraco.functools-3.4.0 jaraco.logging-3.1.0 jaraco.stream-3.0.3 jaraco.text-3.6.0 mautrix-0.11.4 python-socks-2.0.0 tempora-4.1.2

They've also raised the upper limit already, so even if that is an issue, it will be resolved in their next release: https://github.com/hifi/heisenbridge/commit/cff5d33e0b617e6cf3a44dc00c72b98743175c9e

**Comment by Salamandar** [comment]
Yes, that's also really weird because the hard limit <3.8 allowed me to manually install 3.8.1… pip is weird in its own way I think.

**Comment by Dreamsorcerer** [comment]
You can manually install whatever version you want. Pip should give a warning about versions conflicts, but it won't stop you.

**Comment by asvetlov** [comment]
What is `pip` version?
Old is really weird and buggy, I can confirm. The recent is much better.

**Comment by Salamandar** [comment]
I redid what I did yesterday : 
```
$ python3 -m venv totovenv
$ source totovenv/bin/activate
$ python3 -m pip install heisenbridge
Collecting heisenbridge
  Downloading https://files.pythonhosted.org/packages/47/1f/76b9bc58af740bf36bb1414f4da6b2f9f38d6aab35d68f8b3c02ede740f9/heisenbridge-1.7.1-py3-none-any.whl (61kB)
    100% |████████████████████████████████| 61kB 1.3MB/s 
Collecting aiohttp<3.8,>=3.6 (from heisenbridge)
  Downloading https://files.pythonhosted.org/packages/99/f5/90ede947a3ce2d6de1614799f5fea4e93c19b6520a59dc5d2f64123b032f/aiohttp-3.7.4.post0.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 546kB/s 
  Installing build dependencies ... done
Collecting python-socks[asyncio]>=1.2.4 (from heisenbridge)
  Downloading https://files.pythonhosted.org/packages/c9/77/ae7fbd73ea74c7ce7e15bc48e68ba9240d5b637419323c6c8008522ebf0f/python_socks-2.0.0-py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 3.9MB/s 
Collecting pyyaml<5.5,>=5.3 (from heisenbridge)
  Downloading https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz (175kB)
    100% |████████████████████████████████| 184kB 3.2MB/s 
  Installing build dependencies ... done
Collecting irc<20.0,>=19.0.0 (from heisenbridge)
  Downloading https://files.pythonhosted.org/packages/28/bf/a742474848d85e3b5a09dabad64c315a13b668a89f4bec4935a11f727660/irc-19.0.1-py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 4.9MB/s 
Collecting mautrix<0.12,>=0.10.5 (from heisenbridge)
  Downloading https://files.pythonhosted.org/packages/ae/3d/5895438ed031cefe958b1f1c1166a1378ed563bf5641b4b725857215a89a/mautrix-0.11.4-py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 2.3MB/s 
Collecting attrs>=17.3.0 (from aiohttp<3.8,>=3.6->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/20/a9/ba6f1cd1a1517ff022b35acd6a7e4246371dfab08b8e42b829b6d07913cc/attrs-21.2.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 4.7MB/s 
Collecting chardet<5.0,>=2.0 (from aiohttp<3.8,>=3.6->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl (178kB)
    100% |████████████████████████████████| 184kB 3.0MB/s 
Collecting multidict<7.0,>=4.5 (from aiohttp<3.8,>=3.6->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/8e/7c/e12a69795b7b7d5071614af2c691c97fbf16a2a513c66ec52dd7d0a115bb/multidict-5.2.0.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 4.4MB/s 
  Installing build dependencies ... done
Collecting async_timeout<4.0,>=3.0 (from aiohttp<3.8,>=3.6->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp<3.8,>=3.6->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/f6/da/46d1b3d69a9a0835dabf9d59c7eb0f1600599edd421a4c5a15ab09f527e0/yarl-1.7.2.tar.gz (168kB)
    100% |████████████████████████████████| 174kB 2.3MB/s 
  Installing build dependencies ... done
Collecting typing_extensions>=3.6.5 (from aiohttp<3.8,>=3.6->heisenbridge)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/17/61/32c3ab8951142e061587d957226b5683d1387fb22d95b4f69186d92616d1/typing_extensions-4.0.0-py3-none-any.whl
Collecting jaraco.functools>=1.20 (from irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/bc/19/644fb6d99e1a649bc1e427c3028585e659dfef9fe25b2d1b59f959d03164/jaraco.functools-3.4.0-py3-none-any.whl
Collecting more-itertools (from irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/e5/c3/48e2c81038f57e8caab9a6e6fb6c2fc23536c59b092abefc447e6b5d1903/more_itertools-8.12.0-py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 4.7MB/s 
Collecting importlib-metadata; python_version < "3.8" (from irc<20.0,>=19.0.0->heisenbridge)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/c4/1f/e2238896149df09953efcc53bdcc7d23597d6c53e428c30e572eda5ec6eb/importlib_metadata-4.8.2-py3-none-any.whl
Collecting tempora>=1.6 (from irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/be/15/28baf829d3cb94966d89d4e3bb6ef500788d3b0ecbbe331a580ba1157297/tempora-4.1.2-py3-none-any.whl
Collecting pytz (from irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/d3/e3/d9f046b5d1c94a3aeab15f1f867aa414f8ee9d196fae6865f1d6a0ee1a0b/pytz-2021.3-py2.py3-none-any.whl (503kB)
    100% |████████████████████████████████| 512kB 1.3MB/s 
Collecting jaraco.text (from irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/6e/af/ca6e113354ce7a4289b5ec71a8725e92476d33016b9cba130e277c94f302/jaraco.text-3.6.0-py3-none-any.whl
Collecting jaraco.stream (from irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/f6/20/c73c7e4a7f4e4d16cd1039547808b3ce46eae0c491df6166ec4f014004db/jaraco.stream-3.0.3-py3-none-any.whl
Collecting jaraco.logging (from irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/dd/6e/d2b1b31836e89a307549b1df8b51db9b0ced11666f4c821b64e3372c3509/jaraco.logging-3.1.0-py3-none-any.whl
Collecting jaraco.collections (from irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/e9/d5/bcedc8ecd08f0059e82d4fccc8313f1196881eb86b009cc9e3d52d06bf14/jaraco.collections-3.4.0-py3-none-any.whl
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp<3.8,>=3.6->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl (61kB)
    100% |████████████████████████████████| 61kB 4.5MB/s 
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->irc<20.0,>=19.0.0->heisenbridge)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/bd/df/d4a4974a3e3957fd1c1fa3082366d7fff6e428ddb55f074bf64876f8e8ad/zipp-3.6.0-py3-none-any.whl
Collecting importlib-resources; python_version < "3.9" (from jaraco.text->irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/24/1b/33e489669a94da3ef4562938cd306e8fa915e13939d7b8277cb5569cb405/importlib_resources-5.4.0-py3-none-any.whl
Collecting jaraco.classes (from jaraco.collections->irc<20.0,>=19.0.0->heisenbridge)
  Downloading https://files.pythonhosted.org/packages/b8/74/bee5fc11594974746535117546404678fc7b899476e769c3c55bc0cfaa02/jaraco.classes-3.2.1-py3-none-any.whl
Building wheels for collected packages: aiohttp, pyyaml, multidict, yarl
  Running setup.py bdist_wheel for aiohttp ... done
  Stored in directory: /home/admin/.cache/pip/wheels/15/aa/5f/33df380f4940b1c1bda8d83967345fcb97d0749e2cfbb06794
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /home/admin/.cache/pip/wheels/2a/d4/92/cf299bdf4162957ca8126b46e913e29f76a4f17ca762c45028
  Running setup.py bdist_wheel for multidict ... done
  Stored in directory: /home/admin/.cache/pip/wheels/73/7f/38/4d6e62cf67f06a8bb2a69464ee8d7611da2236fd83ce1b33de
  Running setup.py bdist_wheel for yarl ... done
  Stored in directory: /home/admin/.cache/pip/wheels/4b/5b/dc/b5c2dbad09144a8af76e8faf3549084e8d99284388a9439eba
Successfully built aiohttp pyyaml multidict yarl
Installing collected packages: attrs, chardet, multidict, async-timeout, idna, typing-extensions, yarl, aiohttp, python-socks, pyyaml, more-itertools, jaraco.functools, zipp, importlib-metadata, pytz, tempora, importlib-resources, jaraco.text, jaraco.stream, jaraco.logging, jaraco.classes, jaraco.collections, irc, mautrix, heisenbridge
Successfully installed aiohttp-3.7.4.post0 async-timeout-3.0.1 attrs-21.2.0 chardet-4.0.0 heisenbridge-1.7.1 idna-3.3 importlib-metadata-4.8.2 importlib-resources-5.4.0 irc-19.0.1 jaraco.classes-3.2.1 jaraco.collections-3.4.0 jaraco.functools-3.4.0 jaraco.logging-3.1.0 jaraco.stream-3.0.3 jaraco.text-3.6.0 mautrix-0.11.4 more-itertools-8.12.0 multidict-5.2.0 python-socks-2.0.0 pytz-2021.3 pyyaml-5.4.1 tempora-4.1.2 typing-extensions-4.0.0 yarl-1.7.2 zipp-3.6.0
$ python3 -m pip --version
pip 18.1 from /home/admin/totovenv/lib/python3.7/site-packages/pip (python 3.7)
$ # Yes ok that's kinda old
```

And weirdly enough I didn't have the issue :o :o
