### ISSUE TITLE
Use of `base_url` causes `TypeError`

### ISSUE THREAD

**Issue by amikrop** [fafhrd91/aiohttp#6326]
### Describe the bug

Passing a base URL to `ClientSession` causes `TypeError: __init__() takes 1 positional argument but 2 were given`.

### To Reproduce

```
$ python -m asyncio
asyncio REPL 3.8.9 (default, Apr  3 2021, 01:02:10) 
[GCC 5.4.0 20160609] on linux
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> import aiohttp
>>> async with aiohttp.ClientSession("http://google.com") as session:
...     pass
... 
```

### Expected behavior

That it actually works as demonstrated on https://docs.aiohttp.org/en/stable/client_quickstart.html#make-a-request (snippet above the Note).

### Logs/tracebacks

```python-traceback
Exception ignored in: <function ClientSession.__del__ at 0x7f2bec556b80>
Traceback (most recent call last):
  File "/ommited/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 269, in __del__
    if not self.closed:
  File "/ommited/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 894, in closed
    return self._connector is None or self._connector.closed
AttributeError: _connector
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
```

### Python Version

```console
$ python --version
Python 3.8.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 4.0.0a1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /ommited/.venv/lib/python3.8/site-packages
Requires: typing-extensions, multidict, chardet, async-timeout, yarl, attrs
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /ommited/.venv/lib/python3.8/site-packages
Requires: 
Required-by: yarl, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /ommited/.venv/lib/python3.8/site-packages
Requires: multidict, idna
Required-by: aiohttp
```

### OS

Ubuntu 16.04

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> ```
> Version: 4.0.0a1
> ```

That release is over 2 years old, the documentation you are referring to is for 3.8. You'll need to either use the 3.8 release, or run from master. There have not been any recent prereleases of v4.
