### ISSUE TITLE
Confusing about python3.10 SSL certificates

### ISSUE THREAD

**Issue by deknowny** [fafhrd91/aiohttp#6327]
### Describe the bug

`python3.10` drops support of creating `ssl.SSLContext()` without `protocol=` argument. It shows `DeprecationWarning`:
```
/some/my/path/file.py:63: DeprecationWarning: ssl.SSLContext() without protocol argument is deprecated.
    url, ssl=ssl.SSLContext()
```
When I try to use `aiohttp` like this:
```python
async with self.session.post(
     url, data=form_data, ssl=ssl.SSLContext()
) as response:
```
***
I found a bug report about this: https://bugs.python.org/issue44362 
> You either use TLS_PROTOCOL_CLIENT for a client-side socket or TLS_PROTOCOL_SERVER for a server-side socket. TLS_PROTOCOL_CLIENT gives you a secure context for client connections with cert and hostname verification.

And there should be a solution if I will create context instance with this param (a mistake in his message: no `TLS_PROTOCOL_CLIENT` exists, only `PROTOCOL_TLS_CLIENT`):
```python
ssl.SSLContext(protocol=ssl.PROTOCOL_TLS_CLIENT)
```
But I get such error (full stack trace below in issue):
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
```
***
I use MacOS and I found this question on stackoverflow: https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate and I run `Install Certificates.command`. This doesn't work (because I used python in a venv, I recreate a venv but it doesn't help)

In `python3.9` and earlier `Install Certificates.command` works correctly and I could use `aiohttp` without `ssl.SSLContext()` at all.

So there is no way of correct ssl client usage without warning/errors

### To Reproduce

1. Try to make a request on MacOS like this with selected ssl protocol on `python3.10` as said in bug report response:
```python
async with self.session.post(
    url, data=form_data, ssl=ssl.SSLContext(protocol=ssl.PROTOCOL_TLS_CLIENT)
) as response:
    return await response.read()
```

### Expected behavior

No warnings and errors

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/Users/an/Desktop/demapi/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1080, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1110, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 974, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/an/Desktop/demapi/examples/coroutine.py", line 21, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/an/Desktop/demapi/examples/coroutine.py", line 15, in main
    image = await conf.coroutine_download()
  File "/Users/an/Desktop/demapi/demapi/configure/view.py", line 64, in coroutine_download
    return await self.loader.coroutine_download(payload, session)
  File "/Users/an/Desktop/demapi/demapi/loader.py", line 47, in coroutine_download
    preview_page = await connector.post(
  File "/Users/an/Desktop/demapi/demapi/connector/coroutine.py", line 56, in post
    async with self.session.post(
  File "/Users/an/Desktop/demapi/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/Users/an/Desktop/demapi/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/Users/an/Desktop/demapi/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/an/Desktop/demapi/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/an/Desktop/demapi/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/an/Desktop/demapi/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/an/Desktop/demapi/.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.imgonline.com.ua:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
```
```


### Python Version

```console
3.10
```

### aiohttp Version

```console
3.8.1
```

### multidict Version

```console
5.2.0
```

### yarl Version

```console
1.7.2
```

### OS

macOS

### Related component

Client

### Additional context

No proxies. Everything works with `python3.9` and earlier and `ssl.SSLContext()` instance without protocol argument

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> `python3.10` drops support of creating `ssl.SSLContext()` without `protocol=` argument. It shows `DeprecationWarning`:

From the documentation, it looks like `ssl.SSLContext(ssl.PROTOCOL_TLS)` is the same as `ssl.SSLContext()`:
https://docs.python.org/3/library/ssl.html#ssl.SSLContext

This appears to have nothing to do with aiohttp though and I'm not sure what you want us to do. If there's an issue with `SSLContext`, then file a bug against python?

**Comment by deknowny** [comment]
It looks the same. `python3.10` require to pass `ssl.PROTOCOL_TLS`, but `aiohttp` drops a traceback with `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)`

Everything OK with `requests`. I can't find a solution of usage `aiohttp` on `python3.10` with no ssl warnings/errors

**Comment by Dreamsorcerer** [comment]
I'm afraid that installing the certificates can be a pain on Mac OS X sometimes, but without certificates, you can't verify if the connection is secure.

I don't know if something like this might be a workaround? https://github.com/aio-libs/aiohttp/issues/955#issuecomment-568425975

**Comment by deknowny** [comment]
It helps! Thanks

**Comment by asvetlov** [comment]
I use `certifi` on my job for CLI tool, works fine.
The downside of this approach is keeping certificates up to date. 
For example, we have a runtime check that raises a warning if `certifi` version is older than the latest one published on PyPI (similar to `pip` behavior).

It can be done right in *application*; but aiohttp as a *library* cannot check `certifi` correctness.
That's why we don't use this configuration *by default*.

Please feel free to make a documentation pull request with the mentioned hint, it makes a value.

**Comment by deknowny** [comment]
Thank you for the explanation, I wanted to ask a question about default ssl context 😃 ! 

Yes, it should be mentioned in the docs. I will create a PR soon

**Comment by Yalchin403** [comment]
> I'm afraid that installing the certificates can be a pain on Mac OS X sometimes, but without certificates, you can't verify if the connection is secure.
> 
> I don't know if something like this might be a workaround? [#955 (comment)](https://github.com/aio-libs/aiohttp/issues/955#issuecomment-568425975)

This one solved issue with `websocket.connect` method
