### ISSUE TITLE
3.8.1: cythonize make target does not work

### ISSUE THREAD

**Issue by kloczek** [fafhrd91/aiohttp#6398]
### Describe the bug

I've been told in https://github.com/aio-libs/aiohttp/issues/5626 to run "make cythonize" to generate necessary .c files.
Looks like it does not work.

### To Reproduce

1. unpack tagged git tar ball
2. run "make cythonize"

### Expected behavior

Should generate all necessary .c fiels.

### Logs/tracebacks

```python-traceback
+ make cythonize
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.3.1)
re-hash /home/tkloczko/rpmbuild/BUILD/aiohttp-3.8.1/requirements/cython.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: multidict==5.2.0 in /home/tkloczko/.local/lib/python3.8/site-packages (from -r requirements/multidict.txt (line 1)) (5.2.0)
Requirement already satisfied: typing_extensions==3.7.4.3 in /home/tkloczko/.local/lib/python3.8/site-packages (from -r requirements/typing-extensions.txt (line 1)) (3.7.4.3)
Requirement already satisfied: cython==0.29.24 in /usr/lib64/python3.8/site-packages (from -r requirements/cython.txt (line 3)) (0.29.24)
re-hash /home/tkloczko/rpmbuild/BUILD/aiohttp-3.8.1/tools/gen.py
re-hash /home/tkloczko/rpmbuild/BUILD/aiohttp-3.8.1/aiohttp/hdrs.py
./tools/gen.py
Traceback (most recent call last):
  File "./tools/gen.py", line 23, in <module>
    headers = calc_headers(ROOT)
  File "./tools/gen.py", line 16, in calc_headers
    code = compile(hdrs_file.read_text(), str(hdrs_file), "exec")
  File "/usr/lib64/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib64/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib64/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/aiohttp/hdrs.py'
make: *** [Makefile:57: aiohttp/_find_header.c] Error 1
```

### Python Version

```console
$ python --version
Python 3.8.12
```

### aiohttp Version

```console
$ python -m pip show aiohttp
WARNING: Package(s) not found: aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/tkloczko/.local/lib/python3.8/site-packages
Requires:
Required-by: yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib64/python3.8/site-packages
Requires: idna, multidict
Required-by:
```

### OS

Linux x86/64

### Related component

Server

### Additional context

N/A

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Do you use a Git checkout? Any other version? There's not enough info to guess what's going on.

**Comment by kloczek** [comment]
I'm usimg tagged tar ball autogenerated by github.

**Comment by webknjaz** [comment]
That is not supported because `vendor/llhttp` is a Git submodule and GitHub's Git archives probably don't include it. Either use a Git checkout or the official sdist that contains the full source. https://src.fedoraproject.org/rpms/pyproject-rpm-macros will work with that out of the box.

**Comment by kloczek** [comment]
That is other issue that you are bundling other library code instead using system installed header files.

**Comment by kloczek** [comment]
I'm usimg that patch from Fedora which unbundles that library. Here is that patch
https://src.fedoraproject.org/rpms/python-aiohttp/raw/rawhide/f/unbundle-http-parser.patch

**Comment by webknjaz** [comment]
It's the job of the downstream packagers to change such things. We only maintain what is necessary for the Python ecosystem distributions to work within the standards needed for pip to work. Each downstream distro has its own set of guidelines that we don't have any intention to maintain, it's their responsibility and even if we wanted, we don't have the resources to do this anyway.

**Comment by kloczek** [comment]
OK so what is the problem with using system installed http-parser? Why it was not implemented to use that in first place?

**Comment by webknjaz** [comment]
Keyword: manylinux.

**Comment by kloczek** [comment]
So which one Linux distrinution packages `aiohttp` and uses bundled http-parser?

**Comment by webknjaz** [comment]
We don't package for distros, only for the standard ecosystem that essentially is pip+PyPI. It's downstream packagers' responsibility to package it for their curated repositories.

**Comment by kloczek** [comment]
Just made quick grep across all my spec files:
```console
[tkloczko@ss-desktop SPECS]$ grep 'python3dist(cython)' python* -l | xargs grep BuildRequires| grep -v python3 |grep -v gcc
python-aiohttp.spec:BuildRequires:      http-parser-devel
python-gevent.spec:BuildRequires:       c-ares-devel
python-gevent.spec:BuildRequires:       libev-devel
python-gevent.spec:BuildRequires:       libuv-devel
python-hidapi.spec:BuildRequires:       hidapi-devel
python-hidapi.spec:BuildRequires:       libusbx-devel
python-hidapi.spec:BuildRequires:       systemd-devel
python-htmlpyever.spec:BuildRequires:   cargo
python-lupa.spec:BuildRequires: lua-devel
python-lxml.spec:BuildRequires: pkgconfig
python-lxml.spec:BuildRequires: pkgconfig(libxml-2.0)
python-lxml.spec:BuildRequires: pkgconfig(libxslt)
python-mpi4py.spec:BuildRequires:       openmpi-devel
python-numpy.spec:BuildRequires:        flexiblas-devel
python-numpy.spec:BuildRequires:        lapack-devel
python-pyyaml.spec:BuildRequires:       libyaml-devel
python-uvloop.spec:BuildRequires:       libuv-devel
python-zmq.spec:BuildRequires:  zeromq-devel
````
None of those modules bundles libraries which they are using.
In other words .. by buldling oter project code in sdist actually you are adding more work for other people on packaging layer.

Reall please consider change approach to one of those in above examples.

**Comment by webknjaz** [comment]
Yes, this is how it's supposed to be. It's not our responsibility. Our responsibility is to provide a PEP 517 compliant setup and the rest is up to the distros. I'm not going to accept any more unwanted "advice" or demands. It's a FOSS project, if you want something — maintain it.

**Comment by kloczek** [comment]
> Our responsibility is to provide a PEP 517 compliant setup and the rest is up to the distros.

Issue is that pep517 procedure does not work because cythoniose is not integrated.
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting dependencies for wheel...
*********************
* Accelerated build *
*********************
running egg_info
creating aiohttp.egg-info
writing aiohttp.egg-info/PKG-INFO
writing dependency_links to aiohttp.egg-info/dependency_links.txt
writing requirements to aiohttp.egg-info/requires.txt
writing top-level names to aiohttp.egg-info/top_level.txt
writing manifest file 'aiohttp.egg-info/SOURCES.txt'
reading manifest file 'aiohttp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'vendor'
warning: no files found matching 'aiohttp' anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.lib' found anywhere in distribution
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.a' found anywhere in distribution
warning: no previously-included files matching '*.obj' found anywhere in distribution
warning: no previously-included files found matching 'aiohttp/*.html'
no previously-included directories found matching 'docs/_build'
adding license file 'LICENSE.txt'
writing manifest file 'aiohttp.egg-info/SOURCES.txt'
* Building wheel...
*********************
* Accelerated build *
*********************
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-38
creating build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/__init__.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/abc.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/base_protocol.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/client.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/client_exceptions.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/client_proto.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/client_reqrep.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/client_ws.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/connector.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/cookiejar.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/formdata.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/hdrs.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/helpers.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/http.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/http_exceptions.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/http_parser.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/http_websocket.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/http_writer.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/locks.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/log.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/multipart.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/payload.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/payload_streamer.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/pytest_plugin.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/resolver.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/streams.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/tcp_helpers.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/test_utils.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/tracing.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/typedefs.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_app.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_exceptions.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_fileresponse.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_log.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_middlewares.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_protocol.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_request.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_response.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_routedef.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_runner.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_server.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_urldispatcher.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/web_ws.py -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/worker.py -> build/lib.linux-x86_64-cpython-38/aiohttp
running egg_info
writing aiohttp.egg-info/PKG-INFO
writing dependency_links to aiohttp.egg-info/dependency_links.txt
writing requirements to aiohttp.egg-info/requires.txt
writing top-level names to aiohttp.egg-info/top_level.txt
reading manifest file 'aiohttp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'vendor'
warning: no files found matching 'aiohttp' anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.lib' found anywhere in distribution
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.a' found anywhere in distribution
warning: no previously-included files matching '*.obj' found anywhere in distribution
warning: no previously-included files found matching 'aiohttp/*.html'
no previously-included directories found matching 'docs/_build'
adding license file 'LICENSE.txt'
writing manifest file 'aiohttp.egg-info/SOURCES.txt'
copying aiohttp/_cparser.pxd -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/_find_header.pxd -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/_helpers.pyi -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/_helpers.pyx -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/_http_parser.pyx -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/_http_writer.pyx -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/_websocket.pyx -> build/lib.linux-x86_64-cpython-38/aiohttp
copying aiohttp/py.typed -> build/lib.linux-x86_64-cpython-38/aiohttp
running build_ext
building 'aiohttp._websocket' extension
creating build/temp.linux-x86_64-cpython-38
creating build/temp.linux-x86_64-cpython-38/aiohttp
/usr/bin/gcc -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -D_GNU_SOURCE -fPIC -fwrapv -ffat-lto-objects -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -D_GNU_SOURCE -fPIC -fwrapv -ffat-lto-objects -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -D_GNU_SOURCE -fPIC -fwrapv -ffat-lto-objects -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -I/usr/include/python3.8 -c aiohttp/_websocket.c -o build/temp.linux-x86_64-cpython-38/aiohttp/_websocket.o
cc1: fatal error: aiohttp/_websocket.c: No such file or directory
compilation terminated.
```
In this case missing aiohttp/_websocket.c should be geneteted from aiohttp/_websocket.pyx and build procedore do not handles that.
