### ISSUE TITLE
AttributeError on Payload

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#6476]
### Describe the bug

Is this actually a bug in aiohttp? https://github.com/aio-libs/aiohttp-devtools/issues/251

`response._body` at this point is actually a `StringPayload`, which does not have a `decode` attribute:
https://github.com/aio-libs/aiohttp/blob/3.8/aiohttp/web_response.py#L694

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 514, in start
    resp, reset = await task
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 619, in finish_response
    self.log_access(request, resp, start_time)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 398, in log_access
    self.access_logger.log(request, response, self._loop.time() - time)
  File "/home/ubuntu/hacking/aiohttp-devtools/aiohttp_devtools/runserver/log_handlers.py", line 36, in log
    self.logger.info(msg, extra=self.extra(request, response, time))
  File "/home/ubuntu/hacking/aiohttp-devtools/aiohttp_devtools/runserver/log_handlers.py", line 60, in extra
    response_body=parse_body(response.text or response.body, 'response body'),
  File "/home/ubuntu/.local/lib/python3.8/site-packages/aiohttp/web_response.py", line 694, in text
    return self._body.decode(self.charset or "utf-8")
AttributeError: 'StringPayload' object has no attribute 'decode'
```

**Comment by Dreamsorcerer** [comment]
Probably doesn't help that it accepts `Any` at: https://github.com/aio-libs/aiohttp/blob/3.8/aiohttp/web_response.py#L578
So, most of the code seems to expect the body to by `Optional[bytes]`, but doesn't trigger any type errors.

**Comment by asvetlov** [comment]
Heh. An ability to send Payload overcomplicates things. Again.

Probably you have found a bug.
The question is: what should return `resp.text` for non-string payloads?

P.S. 
`web.Response` has too much if/elif/else checks.
IIRC it hits the performance very much for very simple servers, e.g. sed in [example](https://github.com/aio-libs/aiohttp/blob/master/examples/web_srv.py)

**Comment by Dreamsorcerer** [comment]
They seem to all have a `Payload._value`, so should they just have a `.text()` method which can be used to return/encode that?
