### ISSUE TITLE
Invalid Argument Error

### ISSUE THREAD

**Issue by Nebula1213** [fafhrd91/aiohttp#6639]
### Describe the bug

I get this error in my console ```Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 880, in _resolve_host
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/resolver.py", line 33, in resolve
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
OSError: [Errno 22] Invalid argument```

### To Reproduce

I am running a discord bot using disnake

### Expected behavior

I would expect this error not to occur

### Logs/tracebacks

```python-traceback
(most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 880, in _resolve_host
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/resolver.py", line 33, in resolve
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
OSError: [Errno 22] Invalid argument
```

### Python Version

```console
3.8.10
```

### aiohttp Version

```console
3.8.1
```

### multidict Version

```console
6.0.2
```

### yarl Version

```console
1.7.2
```

### OS

ubuntu 20.04

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by CharlieS1103** [comment]
@Nebulizer1213 You ever end up finding a fix for this?
