### ISSUE TITLE
TypeError: Cannot serialize non-str key None

### ISSUE THREAD

**Issue by shehrozkapoor** [fafhrd91/aiohttp#6649]
### Describe the bug

![Screenshot 2022-03-04 at 9 32 14 PM](https://user-images.githubusercontent.com/59894229/156802078-a7cc93fe-6fb1-42b0-a706-61b1379354c8.png)
i am getting the response from the server but the response header is in multidict and it saying that cannot serialize non-str key but when i convert it to str it still gave the same that cannot serialize non-str key None

### To Reproduce

![Uploading Screenshot 2022-03-04 at 9.34.46 PM.png…]()

### Expected behavior

i expected to get print the patients count that is received in the status line

### Logs/tracebacks

```python-traceback
>>> from billing.fhir import main
>>> import asyncio
>>> loop = asyncio.new_event_loop()
>>> loop.run_until_complete(main())
this is header i am recieving <CIMultiDict('Host': 'hapi.fhir.org', 'Authorization': None, 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.8.1')>
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/billing/fhir.py", line 14, in main
    resource_count = await resources.count()
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/fhirpy/base/lib.py", line 282, in count
    await self.client._fetch_resource(self.resource_type, params=new_params)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/fhirpy/base/lib.py", line 130, in _fetch_resource
    return await self._do_request("get", path, params=params)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/fhirpy/base/lib.py", line 112, in _do_request
    async with aiohttp.request(method, url, json=data, headers=headers) as r:
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1186, in __aenter__
    self._resp = await self._coro
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/client.py", line 557, in _request
    resp = await req.send(conn)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 669, in send
    await writer.write_headers(status_line, self.headers)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/http_writer.py", line 139, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None
>>> >>> .run_until_complete(main())n())
this is header i am recieving <CIMultiDict('Host': 'hapi.fhir.org', 'Authorization': None, 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.8.1')>
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/billing/fhir.py", line 14, in main
    resource_count = await resources.count()
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/fhirpy/base/lib.py", line 282, in count
    await self.client._fetch_resource(self.resource_type, params=new_params)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/fhirpy/base/lib.py", line 130, in _fetch_resource
    return await self._do_request("get", path, params=params)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/fhirpy/base/lib.py", line 112, in _do_request
    async with aiohttp.request(method, url, json=data, headers=headers) as r:
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1186, in __aenter__
    self._resp = await self._coro
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/client.py", line 557, in _request
    resp = await req.send(conn)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 669, in send
    await writer.write_headers(status_line, self.headers)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/http_writer.py", line 139, in write_headers
    buf = _serialize_headers(status_line, str(headers))
  File "aiohttp/_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None
>>> loop.run_until_complete(main())
this is header i am recieving <CIMultiDict('Host': 'hapi.fhir.org', 'Authorization': None, 'Accept': 'application/json', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.8.1')>
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/billing/fhir.py", line 14, in main
    resource_count = await resources.count()
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/fhirpy/base/lib.py", line 282, in count
    await self.client._fetch_resource(self.resource_type, params=new_params)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/fhirpy/base/lib.py", line 130, in _fetch_resource
    return await self._do_request("get", path, params=params)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/fhirpy/base/lib.py", line 112, in _do_request
    async with aiohttp.request(method, url, json=data, headers=headers) as r:
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1186, in __aenter__
    self._resp = await self._coro
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/client.py", line 557, in _request
    resp = await req.send(conn)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 669, in send
    await writer.write_headers(status_line, self.headers)
  File "/Users/shehrozkapoor/Desktop/FIRST_CARE/firstcare/venv/lib/python3.8/site-packages/aiohttp/http_writer.py", line 139, in write_headers
    buf = _serialize_headers(status_line, str(headers))
  File "aiohttp/_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None
```

### Python Version

```console
$ python --version
Python 3.8.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.2
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
```

### OS

macOS

### Related component

Server, Client

### Additional context

i am using the dajngo i need to implement the fhir i get the header response in multiDict but it cannot serialize the multiDict

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by shehrozkapoor** [comment]
i solved this bug there was the because in the header for authorization there is None and it cannot serialize it the None
