### ISSUE TITLE
EmptyStreamReader instances raise an exception when printed

### ISSUE THREAD

**Issue by wmsmith** [fafhrd91/aiohttp#6655]
### Describe the bug

I have code that uses `aiohttp` and is attempting to log the body of responses.  If the response is an instance of `EmptyStreamReader`, an exception is raised.  

This happens because `EmptyStreamReader` does not define `__str__`, and thus falls back to the `__repr__` it inherits from its parent (`StreamReader`), which reads attributes defined in the parent's `__init__` but are not defined for `EmptyStreamReader` since version 3.8.0 (commit https://github.com/aio-libs/aiohttp/pull/5270/commits/dac7994d9afce3dd43948a47162f9c7633ecf38a) when code was added to prevent executing the parent's `__init__`.

### To Reproduce

1.  Create an instance of `EmptyStreamReader`
2. Try to print the instance

Eg:
```
>>> from aiohttp.streams import EmptyStreamReader
>>> es = EmptyStreamReader()
>>> print(es)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wayne/development/aiohttp/aiohttp/streams.py", line 130, in __repr__
    if self._size:
AttributeError: 'EmptyStreamReader' object has no attribute '_size'
```

### Expected behavior

The instance of `EmptyStreamReader` should not raise when printed.  

### Logs/tracebacks

```python-traceback
[ERROR] AttributeError: 'EmptyStreamReader' object has no attribute '_size'
Traceback (most recent call last):
  File "/var/task/main.py", line 115, in handler
    event_loop.run_until_complete(asyncio.gather(*tasks))
  File "/var/lang/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/var/task/aiobotocore/client.py", line 89, in _make_api_call
    operation_model, request_dict, request_context)
  File "/var/task/aiobotocore/client.py", line 110, in _make_request
    request_dict)
  File "/var/task/aiobotocore/endpoint.py", line 73, in _send_request
    request, operation_model, context)
  File "/var/task/aiobotocore/endpoint.py", line 106, in _get_response
    request, operation_model)
  File "/var/task/aiobotocore/endpoint.py", line 164, in _do_get_response
    response_dict, operation_model.output_shape)
  File "/var/task/botocore/parsers.py", line 235, in parse
    LOG.debug('Response body:\n%s', response['body'])
  File "/var/lang/lib/python3.7/logging/__init__.py", line 1366, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/var/runtime/bootstrap.py", line 239, in emit
    msg = self.format(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/var/lang/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/var/lang/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
  File "/var/task/wrapt/wrappers.py", line 117, in __str__
    return str(self.__wrapped__)
  File "/var/task/wrapt/wrappers.py", line 117, in __str__
    return str(self.__wrapped__)
  File "/var/task/aiohttp/streams.py", line 132, in __repr__
    if self._size:
[ERROR] AttributeError: 'EmptyStreamReader' object has no attribute '_size' Traceback (most recent call last):   File "/var/task/main.py", line 115, in handler     event_loop.run_until_complete(asyncio.gather(*tasks))   File "/var/lang/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete     return future.result()   File "/var/task/aiobotocore/client.py", line 89, in _make_api_call     operation_model, request_dict, request_context)   File "/var/task/aiobotocore/client.py", line 110, in _make_request     request_dict)   File "/var/task/aiobotocore/endpoint.py", line 73, in _send_request     request, operation_model, context)   File "/var/task/aiobotocore/endpoint.py", line 106, in _get_response     request, operation_model)   File "/var/task/aiobotocore/endpoint.py", line 164, in _do_get_response     response_dict, operation_model.output_shape)   File "/var/task/botocore/parsers.py", line 235, in parse     LOG.debug('Response body:\n%s', response['body'])   File "/var/lang/lib/python3.7/logging/__init__.py", line 1366, in debug     self._log(DEBUG, msg, args, **kwargs)   File "/var/lang/lib/python3.7/logging/__init__.py", line 1514, in _log     self.handle(record)   File "/var/lang/lib/python3.7/logging/__init__.py", line 1524, in handle     self.callHandlers(record)   File "/var/lang/lib/python3.7/logging/__init__.py", line 1586, in callHandlers     hdlr.handle(record)   File "/var/lang/lib/python3.7/logging/__init__.py", line 894, in handle     self.emit(record)   File "/var/runtime/bootstrap.py", line 239, in emit     msg = self.format(record)   File "/var/lang/lib/python3.7/logging/__init__.py", line 869, in format     return fmt.format(record)   File "/var/lang/lib/python3.7/logging/__init__.py", line 608, in format     record.message = record.getMessage()   File "/var/lang/lib/python3.7/logging/__init__.py", line 369, in getMessage     msg = msg % self.args   File "/var/task/wrapt/wrappers.py", line 117, in __str__     return str(self.__wrapped__)   File "/var/task/wrapt/wrappers.py", line 117, in __str__     return str(self.__wrapped__)   File "/var/task/aiohttp/streams.py", line 132, in __repr__     if self._size:
```

### Python Version

```console
3.7.12
```

### aiohttp Version

```console
3.8.1
```

### multidict Version

```console
6.0.2
```

### yarl Version

```console
1.7.2
```

### OS

Ubuntu

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by cancan101** [comment]
This has been fixed in master: https://github.com/aio-libs/aiohttp/pull/6916, but not backported to 3.8.x branch.
