### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectionError when creating an async generator inside the request context manager

### ISSUE THREAD

**Issue by adnaanbheda** [fafhrd91/aiohttp#6680]
### Describe the bug

```
        async with aiohttp.ClientSession() as client:
            async with client.get(url=URL) as resp:
                async def generator():
                    async for data, _ in resp.content.iter_chunks():
                        yield data
                return generator(), resp.status, resp.headers
```

The purpose is to proxy requests from an ASGI server, the above snippet raises the exception but when you run the snippet without an ASGI server, it works fine, which is very weird. Disregarding the bug I just want to find a way in which I can stream responses along with their status codes and headers.

### To Reproduce

```
import quart
import aiohttp

# import uvicorn

# import fastapi
# from fastapi.responses import StreamingResponse

URL = "https://httpbin.org/json"

app = quart.Quart(__name__)
# app = fastapi.FastAPI()


@app.get("/aiohttp")
async def aiohttp_test():

    session = aiohttp.ClientSession()
    async with session.request(method="get", url=URL) as resp:

        async def generator():
            async for data in resp.content.iter_any():
                yield data

        return generator(), resp.status, dict(resp.headers)
        # return StreamingResponse(generator(), resp.status, dict(resp.headers))


if __name__ == "__main__":
    app.run(port=5000)
    # uvicorn.run(app, port=5000)


```

The error occurs across frameworks like Quart, FastAPI and ASGI servers like Hypercorn and Uvicorn

### Expected behavior

Tuple containing the async generator, status code, and headers, so as to create a "Flask like" response containing content, status, headers

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/hypercorn/asyncio/task_group.py", line 21, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/hypercorn/utils.py", line 247, in invoke_asgi
    await app(scope, receive, send)
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/quart/app.py", line 1741, in __call__
    await self.asgi_app(scope, receive, send)
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/quart/app.py", line 1767, in asgi_app
    await asgi_handler(receive, send)
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/quart/asgi.py", line 51, in __call__
    _raise_exceptions(done)
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/quart/asgi.py", line 353, in _raise_exceptions
    raise task.exception()
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/quart/asgi.py", line 102, in handle_request
    await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
  File "/home/adnaan/.pyenv/versions/3.9.10/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/quart/asgi.py", line 131, in _send_response
    async for data in response_body:
  File "/home/adnaan/klinify/deploy/global/idk/test_quart_aiohttp.py", line 68, in generator
    async for data, _ in resp.content.iter_chunks():
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/aiohttp/streams.py", line 51, in __anext__
    rv = await self._stream.readchunk()
  File "/home/adnaan/.local/share/virtualenvs/idk-P59nEHUL/lib/python3.9/site-packages/aiohttp/streams.py", line 411, in readchunk
    raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed
```

### Python Version

```console
3.9
```

### aiohttp Version

```console
3.8.1
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
1.7.2
```

### OS

WSL2 - Ubuntu 20.04 

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
The code is clearly broken, the fact that it works in some circumstances is just luck and may change in future versions.

```
    async with session.request(method="get", url=URL) as resp:
        async def generator():
            async for data in resp.content.iter_any():
                yield data

        return generator(), resp.status, dict(resp.headers)
```
This code clearly enters a context manager (`async with`), where the expectation is that the connection is closed when exiting the block. You then `return` from the function, thus exiting the block and triggering the connection closure. Then you try to iterate over `resp.content`, which should be expected to fail.

I suspect you just want to put all of that into your generator:
```
    async def generator():
        async with ClientSession() as session:
            async with session.request(method="get", url=URL) as resp:
                async for data in resp.content.iter_any():
                    yield data

    return generator(), resp.status, dict(resp.headers)
```

**Comment by Dreamsorcerer** [comment]
Oh, but then you don't have status/headers when you return.

I think it's a bit of a convoluted thing to achieve, but you could maybe do something like this instead:
```
    async def generator():
        async with ClientSession() as session:
            async with session.request(method="get", url=URL) as resp:
                yield resp.status, resp.headers
                async for data in resp.content.iter_any():
                    yield data

    gen = generator()
    status, headers = await anext(gen)
    return gen, status, dict(headers)
```
