### ISSUE TITLE
`content-encoding: br` header sent when brotli isn't installed.

### ISSUE THREAD

**Issue by TheOnlyWayUp** [fafhrd91/aiohttp#6705]
### Describe the bug

Brotli's br header is used even when brotli isn't installed, and the error is quite misleading.
```py
Traceback (most recent call last):
  File "C:\Users\User\ki\discord.py-self\examples\reply.py", line 19, in <module>
    client.run('mytoken')
  File "C:\Python310\lib\site-packages\discord\client.py", line 715, in run
    asyncio.run(runner())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\discord\client.py", line 712, in runner
    await self.start(*args, **kwargs)
  File "C:\Python310\lib\site-packages\discord\client.py", line 685, in start
    await self.login(token)
  File "C:\Python310\lib\site-packages\discord\client.py", line 553, in login
    data = await state.http.static_login(token.strip())
  File "C:\Python310\lib\site-packages\discord\http.py", line 650, in static_login
    await self.startup()
  File "C:\Python310\lib\site-packages\discord\http.py", line 372, in startup
    self.user_agent, self.browser_version, self.client_build_number = ua, bv, bn = await utils._get_info(session)
  File "C:\Python310\lib\site-packages\discord\utils.py", line 1242, in _get_info
    bn = await _get_build_number(session)
  File "C:\Python310\lib\site-packages\discord\utils.py", line 1251, in _get_build_number
    login_page = await login_page_request.text()
  File "C:\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 1076, in text
    await self.read()
  File "C:\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "C:\Python310\lib\site-packages\aiohttp\streams.py", line 344, in read
    raise self._exception
aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'
```
Brotli isn't installed on the system and it *doesn't* seem to be an issue with the webserver (discord) from my testing.

### To Reproduce

Clone https://github.com/dolfies/discord.py-self/, cd into the examples directory, modify the reply.py to include your user token (last line) and run the file.

### Expected behavior

The aiohttp client shouldn't send the `content-encoding: br` header to the webserver.

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "C:\Users\User\ki\discord.py-self\examples\reply.py", line 19, in <module>
    client.run('mytoken')
  File "C:\Python310\lib\site-packages\discord\client.py", line 715, in run
    asyncio.run(runner())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\discord\client.py", line 712, in runner
    await self.start(*args, **kwargs)
  File "C:\Python310\lib\site-packages\discord\client.py", line 685, in start
    await self.login(token)
  File "C:\Python310\lib\site-packages\discord\client.py", line 553, in login
    data = await state.http.static_login(token.strip())
  File "C:\Python310\lib\site-packages\discord\http.py", line 650, in static_login
    await self.startup()
  File "C:\Python310\lib\site-packages\discord\http.py", line 372, in startup
    self.user_agent, self.browser_version, self.client_build_number = ua, bv, bn = await utils._get_info(session)
  File "C:\Python310\lib\site-packages\discord\utils.py", line 1242, in _get_info
    bn = await _get_build_number(session)
  File "C:\Python310\lib\site-packages\discord\utils.py", line 1251, in _get_build_number
    login_page = await login_page_request.text()
  File "C:\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 1076, in text
    await self.read()
  File "C:\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "C:\Python310\lib\site-packages\aiohttp\streams.py", line 344, in read
    raise self._exception
aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'


```py
Traceback (most recent call last):
  File "/home/user/Desktop/HTML/danktrivia/trivia.py", line 27, in <module>
    client.run("<REMOVED>")
  File "/home/user/.local/lib/python3.9/site-packages/discord/client.py", line 654, in run
    return future.result()
  File "/home/user/.local/lib/python3.9/site-packages/discord/client.py", line 633, in runner
    await self.start(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/discord/client.py", line 596, in start
    await self.login(token)
  File "/home/user/.local/lib/python3.9/site-packages/discord/client.py", line 471, in login
    data = await state.http.static_login(token.strip())
  File "/home/user/.local/lib/python3.9/site-packages/discord/http.py", line 452, in static_login
    await self.startup()
  File "/home/user/.local/lib/python3.9/site-packages/discord/http.py", line 207, in startup
    self.user_agent, self.browser_version, self.client_build_number = ua, bv, bn = await utils._get_info(session)
  File "/home/user/.local/lib/python3.9/site-packages/discord/utils.py", line 1265, in _get_info
    bn = await _get_build_number(session)
  File "/home/user/.local/lib/python3.9/site-packages/discord/utils.py", line 1274, in _get_build_number
    login_page = await login_page_request.text()
  File "/home/user/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1076, in text
    await self.read()
  File "/home/user/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "/home/user/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 344, in read
    raise self._exception
aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'
```
```


### Python Version

```console
Python 3.10.4
```

### aiohttp Version

```console
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /root/code/Bots/dpys_test/venv/lib/python3.10/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by: discord.py-self
```

### multidict Version

```console
Name: multidict
Version: 6.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /root/code/Bots/dpys_test/venv/lib/python3.10/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /root/code/Bots/dpys_test/venv/lib/python3.10/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Ubuntu

### Related component

Client

### Additional context

dolfies/discord.py-self#236
dolfies/discord.py-self#275
have a bit more discussion on this.

Made this issue mostly to figured out why this is happening and if it was fixed.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
In https://github.com/dolfies/discord.py-self/discussions/236 you say it was fixed after upgrading aiohttp. So, isn't the problem fixed then? There were a number of issues present in 3.7, so maybe best to bump the requirements in that project to >=3.8.
