### ISSUE TITLE
Cannot connect to host [No such file or directory]

### ISSUE THREAD

**Issue by ohitstom** [fafhrd91/aiohttp#6754]
### Describe the bug

Problem:
Seemingly random no such file or directory errors when downloading/requesting a file from a website.
![image](https://user-images.githubusercontent.com/22730962/168689442-0b61fdb2-6ae3-4530-bae4-b974eb07d117.png)

Function:
[https://github.com/ohitstom/spicetify-easyinstall/blob/Spicetify-v2/modules/utils.py#L223#L264](url)

Example Usage:
![image](https://user-images.githubusercontent.com/22730962/168689686-043636a4-fe03-4537-bf23-1cbe431115eb.png)
(globals.temp + "\\" + globals.SPOTIFY_VERSION = C:\\Users\\tomfi\\AppData\\Local\\Temp\\spicetifyversion.353.43.34)

Notes:
This isnt a consistent error, its not like the code is the problem (atleast i hope), using a vpn seems to fix the issue for some users so im entirely unsure how or why this is happening

### To Reproduce

1. Try to create a chunked download using aio
2. Random errors
3. Barely any error information

### Expected behavior

A clear and concise error that i am able to troubleshoot with

### Logs/tracebacks

```python-traceback
above
```

### Python Version

```console
$ python --version
3.9.7
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.7.4.post0
```

### multidict Version

```console
$ python -m pip show multidict
not installed
```

### yarl Version

```console
$ python -m pip show yarl
1.7.2
```

### OS

Windows 10

### Related component

Client

### Additional context

I would just appreciate more error information or for someone to explain this issue to me because i cant find anyone with the same problem online

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> ### aiohttp Version
> 
> ```
> $ python -m pip show aiohttp
> 3.7.4.post0
> ```

I'd suggest updating to the latest release as the very first thing to test. There are a number of known issues in the 3.7 release that never got backported unfortunately.

**Comment by Dreamsorcerer** [comment]
Although it is rather unclear what the no such file refers to. Appears there are other reports in relation to Python's SSL, such as: https://stackoverflow.com/questions/63508878/python-intermittent-openssl-error-filenotfounderror-errno-2-no-such-file-or

But, what is the first exception? Can you paste the full output from the traceback?

**Comment by ohitstom** [comment]
Thanks for the reply!

The error is as follows ```(4/10) Downloading correct Spotify version...
Traceback (most recent call last):
  File "aiohttp\connector.py", line 1154, in _create_direct_connection
  File "aiohttp\connector.py", line 880, in _resolve_host
  File "aiohttp\resolver.py", line 33, in resolve
  File "asyncio\base_events.py", line 856, in getaddrinfo
  File "qasync\__init__.py", line 149, in run
  File "socket.py", line 954, in getaddrinfo
  File "encodings\__init__.py", line 98, in search_function
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1388, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1369, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 423, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 716, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 536, in _get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rngfu\\AppData\\Local\\Temp\\Rar$EXa20268.48396\\base_library.zip'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "modules\screens.py", line 203, in shownCallback
  File "modules\core.py", line 90, in install
  File "modules\utils.py", line 197, in chunked_download
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 535, in _request
  File "aiohttp\connector.py", line 542, in connect
  File "aiohttp\connector.py", line 907, in _create_connection
  File "aiohttp\connector.py", line 1166, in _create_direct_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host upgrade.scdn.co:443 ssl:default [No such file or directory]```

It's some very weird behaviour and Im not sure what's causing it, I also cant replicate it and it's strange a VPN fixes it for most...

**Comment by ohitstom** [comment]
@Dreamsorcerer any idea?

**Comment by Dreamsorcerer** [comment]
Only that it appears like something wrong with SSL in Python as mentioned before. Your traceback appears to confirm that the error is coming from stdlib, not our code. I'm not sure if there is anything we can do with our code to resolve the issue or not.

**Comment by Dreamsorcerer** [comment]
While the filenames are gone in the end of your traceback, it looks like this is the line at end of the traceback where the error originally comes from:
https://github.com/python/cpython/blob/3.9/Lib/zipimport.py#L536

**Comment by Dreamsorcerer** [comment]
Given the lack of a reproducer and the above information, it seems like reporting the bug to cpython may be more relevant. I don't think we can do anything with this.
