### ISSUE TITLE
RuntimeError: coroutine ignored GeneratorExit

### ISSUE THREAD

**Issue by superarray** [fafhrd91/aiohttp#6780]
### Describe the bug

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 985, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
RuntimeError: coroutine ignored GeneratorExit

### To Reproduce

I don't know why this problem occurs, it feels like asyncio socks problem

### Expected behavior

 no

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 985, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
RuntimeError: coroutine ignored GeneratorExit


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/cookiejar.py", line 113, in clear
    to_del = []
RuntimeError: coroutine ignored GeneratorExit


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/cookiejar.py", line 114, in clear
    now = datetime.datetime.now(datetime.timezone.utc)
RuntimeError: coroutine ignored GeneratorExit
```

### Python Version

```console
$ python --version
Python 3.9.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: None
Author-email: None
License: Apache 2
Location: /usr/local/lib/python3.9/site-packages
Requires: async-timeout, frozenlist, yarl, aiosignal, attrs, charset-normalizer, multidict
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.9/site-packages
Requires: 
Required-by: yarl, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/bounty.gonder/.local/lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Centos 7

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
You've provided almost no information. Please include the full traceback and the code that produces the problem..
