### ISSUE TITLE
set_wakeup_fd only works in main thread

### ISSUE THREAD

**Issue by Timtaran** [fafhrd91/aiohttp#6783]
### Describe the bug

WebServer don't starts on Linux

### To Reproduce

use this code:
```python3
routes = web.RouteTableDef()
@routes.get('/{nickname}')
async def hello(request):
	print("I delete this code bcs it's dont except error")

def start_http_server():
	app = web.Application()
	app.add_routes(routes)
	web.run_app(app, port=25550)
async def pre_start_http_server():
	print('hi')
	bot.loop.run_in_executor(None, start_http_server)

@bot.event
async def on_ready():
	print('bot started')
	bot.loop.create_task(pre_start_http_server())
```

### Expected behavior

pycord will work with aiohttp server together

### Logs/tracebacks

```python-traceback
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-20' coro=<_run_app() done, defined at /home/container/.local/lib/python3.8/site-packages/aiohttp/web.py:287> exception=RuntimeError('set_wakeup_fd only works in main thread')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 95, in add_signal_handler
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/web.py", line 514, in run_app
    loop.run_until_complete(main_task)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/web.py", line 321, in _run_app
    await runner.setup()
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/web_runner.py", line 273, in setup
    loop.add_signal_handler(signal.SIGINT, _raise_graceful_exit)
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 97, in add_signal_handler
    raise RuntimeError(str(exc))
RuntimeError: set_wakeup_fd only works in main thread
Future exception was never retrieved
future: <Future finished exception=RuntimeError('set_wakeup_fd only works in main thread')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 95, in add_signal_handler
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/container/main.py", line 60, in start_http_server
    web.run_app(app, port=25550)
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/web.py", line 514, in run_app
    loop.run_until_complete(main_task)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/web.py", line 321, in _run_app
    await runner.setup()
  File "/home/container/.local/lib/python3.8/site-packages/aiohttp/web_runner.py", line 273, in setup
    loop.add_signal_handler(signal.SIGINT, _raise_graceful_exit)
  File "/usr/local/lib/python3.8/asyncio/unix_events.py", line 97, in add_signal_handler
    raise RuntimeError(str(exc))
RuntimeError: set_wakeup_fd only works in main thread
```

### Python Version

```console
$ python --version
Python 3.8.13
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /home/container/.local/lib/python3.8/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/container/.local/lib/python3.8/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/container/.local/lib/python3.8/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Linux 20.04 LTS + Pterodactyl

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Timtaran** [comment]
Ok, so, it's pterodactyl error
