### ISSUE TITLE
Suppositive bug with using proxy in aiohttp.ClientSession

### ISSUE THREAD

**Issue by Vernadskii** [fafhrd91/aiohttp#6835]
### Describe the bug

Hello, I have explored previous issues with 'proxy' topic and didn't find the same problem...
Small description:
1) I have a server on linux where I use curl utility for some connections, additionally, I have `HTTP_PROXY` and `HTTPS_PROXY` (and `http_proxy` and `https_proxy`) environment variables for curl proxy settings. (Ex: http_proxy=**10.252.250.10:3192**)
So, in this way, I don't need to specify my proxy settings for curl requests and every curl request works fine! 
2) I have a python program, which need to use proxy settings from server, I mean from those variables.
Ex:
```
async def get_token() -> str:
       async with aiohttp.ClientSession(trust_env=True) as session:
           async with session.post(
                   "https://test.com/token",
                   data={"123":"456"}) as response:
               pass
asyncio.run(get_token())
```
Documentation says that **`trust_env`=True** --> get proxies information from **HTTP_PROXY / HTTPS_PROXY** environment variables.
And it looks like aiohttp is getting value from proxy variables correctly but can't use it:
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    asyncio.run(get_token())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 7, in get_token
    async with session.post(
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/connector.py", line 905, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 10.252.250.10:3192
```

When I rewrite my script and add: proxy="http://10.252.250.10:3192" it works fine. 
```
async def get_token() -> str:
       async with aiohttp.ClientSession(trust_env=True) as session:
           async with session.post(
                   "https://test.com/token",
                   data={"123":"456"}, proxy="http://10.255.251.1:3128") as response:
               pass
```

It seems like the library doesn't add "**http:://**" part. I compared with `requests `python library without specifying proxy in code  and it works fine! So, I think that it's problem of aiohttp....

### To Reproduce

1)Set variables with proxy
2)Try snipped of code with proxy

### Expected behavior

Should retrieve proxy settings correctly like it do  `requests` library and `curl` utility

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    asyncio.run(get_token())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 7, in get_token
    async with session.post(
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/connector.py", line 905, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/home/techm-admin/ue-sync/venv-ue-sync/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 10.252.250.10:3192
```

### Python Version

```console
$ python --version
Python 3.8.13
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
```

### OS

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
There doesn't appear to be a standard for http_proxy, but the first example I could find when searching uses a complete URI: https://www.golinuxcloud.com/set-up-proxy-http-proxy-environment-variable/

In fact, every example I've found uses a URI:
https://serverfault.com/questions/479178/special-characters-in-http-proxy-environment-variable
https://www.putorius.net/how-to-set-httpproxy-variable-in-linux.html
https://docs.oracle.com/cd/A87860_01/doc/ois.817/a85440/wf/instal25.htm
https://everything.curl.dev/usingcurl/proxies/env
https://askubuntu.com/questions/228530/updating-http-proxy-environment-variable

So, I think the aiohttp behaviour is fine.

**Comment by webknjaz** [comment]
I agree with Sam. Just because some other project implements an exotic feature like this doesn't mean that aiohttp should. 
https://superuser.com/a/1166790/182499 suggests that this env vars convention originated in CURL and if that's the case and there's no other formal standard, that's what we must comply with.

Also, my understanding is that the variable name refers to the protocol used in the client request, not to the protocol used to communicate with the proxy.

`HTTP_PROXY=https://proxy-address.com` would mean that for HTTP requests a proxy reachable over HTTPS would be used. `HTTPS_PROXY=http://proxy-address.com` would mean that requests of HTTPS URLs would use a plain HTTP proxy.
And only `HTTPS_PROXY=https://proxy-address.com` uses TLS-in-TLS.

So no, I don't think it's reasonable to guess the intended proxy protocol when it's not specified. What `requests` does seems inadequate. Closing.

**Comment by Vernadskii** [comment]
Thank you for your prompt response!
