### ISSUE TITLE
Timeout exception when using "async with request('GET')" - but it works with ClientSession

### ISSUE THREAD

**Issue by a2z72** [fafhrd91/aiohttp#6882]
### Describe the bug

Hello,

Thanks for this amazing library.

Here's my code:

```
async with request("GET", url, timeout=TIMEOUT) as response:
    data = await response.text("utf-8")
```

Here's the error I get: `AttributeError: 'int' object has no attribute 'total'`

The same timeout works just fine with the following code:

```
async with aiohttp.ClientSession() as session:
    async with session.get(url, timeout=10) as response:
        data = await response.text("utf-8")
```

### To Reproduce

```async with request("GET", url, timeout=10) as response:
    data = await response.text("utf-8")
```

### Expected behavior

Timeout functionality to work with async with request('GET')

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/Users/me/PycharmProjects/scrapers/my_project/main.py", line 66, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/me/PycharmProjects/scrapers/my_project/main.py", line 61, in main
    async for result in pool.map(check, chunk):
  File "/Users/me/PycharmProjects/scrapers/my_project/venv/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 145, in results_generator
    yield (await self.pool.results([task_id]))[0]
  File "/Users/me/PycharmProjects/scrapers/my_project/venv/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 308, in results
    raise ProxyException(tb)
aiomultiprocess.types.ProxyException: Traceback (most recent call last):
  File "/Users/me/PycharmProjects/scrapers/my_project/venv/lib/python3.8/site-packages/aiomultiprocess/pool.py", line 110, in run
    result = future.result()
  File "/Users/me/PycharmProjects/scrapers/my_project/main.py", line 31, in check
    async with request("GET", url, timeout=10) as response:
  File "/Users/me/PycharmProjects/scrapers/my_project/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1186, in __aenter__
    self._resp = await self._coro
  File "/Users/me/PycharmProjects/scrapers/my_project/venv/lib/python3.8/site-packages/aiohttp/client.py", line 446, in _request
    tm = TimeoutHandle(self._loop, real_timeout.total)
AttributeError: 'int' object has no attribute 'total'
```

### Python Version

```console
$ python --version

Python 3.8.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp

Version: 3.8.1
```

### multidict Version

```console
$ python -m pip show multidict

Version: 6.0.2
```

### yarl Version

```console
$ python -m pip show yarl

Version: 1.8.1
```

### OS

macOS

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Firstly, your broken code is incomplete (what is `request` or `TIMEOUT`?). Please try to provide a complete reproducer.

Secondly, if you check the documentation, it doesn't mention `int` is a valid value for timeout: https://docs.aiohttp.org/en/stable/client_reference.html#client-session
Try using a ClientTimeout. (If you type-checked your code with mypy, it would also tell you that it is wrong).

Not sure why your second example would work though. Looks like it should fail to me.
