### ISSUE TITLE
aiohttp.web has no attribute 'AppKey'

### ISSUE THREAD

**Issue by fibbo** [fafhrd91/aiohttp#6885]
### Describe the bug

Trying to run the example `web_ws.py` and it fails with

```
➜ python web_ws.py
Traceback (most recent call last):
  File "/Users/philippg/tmp/ws_example/web_ws.py", line 14, in <module>
    sockets = web.AppKey("sockets", List[web.WebSocketResponse])
AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
```

```
❯ pip list aiohttp
Package            Version
------------------ ---------
aiohttp            3.8.1
...
```

### To Reproduce

1. Install `aiohttp` 3.8.1
2. Run `https://github.com/aio-libs/aiohttp/blob/master/examples/web_srv.py`

### Expected behavior

Running the application without exception

### Logs/tracebacks

```python-traceback
➜ python web_ws.py
Traceback (most recent call last):
  File "/Users/philippg/tmp/ws_example/web_ws.py", line 14, in <module>
    sockets = web.AppKey("sockets", List[web.WebSocketResponse])
AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
```

### Python Version

```console
➜ python --version
Python 3.10.6
```

### aiohttp Version

```console
➜ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: /Users/philippg/venvs/venv/lib/python3.10/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
➜ python -m pip show multidict
Name: multidict
Version: 6.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/philippg/venvs/venv/lib/python3.10/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
➜ python -m pip show yarl
Name: yarl
Version: 1.8.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/philippg/venvs/venv/lib/python3.10/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

MacOS Monterey, 12.5

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
You're taking the example from master and then running it against v3.8.

Use the 3.8 branch: https://github.com/aio-libs/aiohttp/tree/3.8

AppKey is a new feature in 3.9.
