### ISSUE TITLE
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by openspeedtest** [fafhrd91/aiohttp#6912]
### Describe the bug

````
import asyncio
import io
import os

import aiohttp
from tqdm.asyncio import tqdm


URL = 'http://your-ip:3000/upload'


async def chunks(data, chunk_size):
    with tqdm.wrapattr(io.BytesIO(data), 'read', total=len(data)) as f:
        chunk = f.read(chunk_size)
        while chunk:
            yield chunk
            chunk = f.read(chunk_size)


async def download(session, chunk_size):
    data_to_send = os.urandom(30_000_000)
    data_generator = chunks(data_to_send, chunk_size)
    await session.post(URL, data=data_generator)

        
async def main():
    async with aiohttp.ClientSession() as session:
        tasks = [] 
        for _ in range(5):
            t = asyncio.create_task(download(session, 4096))
            tasks.append(t)
        await asyncio.gather(*tasks)
            

asyncio.run(main())
````
I am trying to make a CLI client for [OpenSpeedTest-Server](https://go.openspeedtest.com/Server)
I am getting same error like this.
to reproduce this use our DOCKER IMAGE or Android App.
then make a post request to "http://your-ip:3000/upload"
issues :
For docker image it will only send first chunk
for Android app it will throw error like this.

````
Traceback (most recent call last):
  File "r.py", line 35, in <module>
    asyncio.run(main())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "r.py", line 32, in main
    await asyncio.gather(*tasks)
  File "r.py", line 23, in download
    await session.post(URL, data=data_generator)
  File "/Users/goredplanet/Library/Python/3.8/lib/python/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/Users/goredplanet/Library/Python/3.8/lib/python/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/goredplanet/Library/Python/3.8/lib/python/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
````
It is working fine when using Electron Apps of OpenSpeedTest-Server (Windows, Mac and Linux GUI Server apps)
it uses Express server.

Mobile Apps uses iOnic WebServer, for Android it's NanoHTTP Server and for iOS it is GDC WebServer.
for Docker we use Nginx WebServer. Configuration posted on my profile.

### To Reproduce

1) Download OpenSpeedTest-Server Android App
2)Run script i posted after changing the IP address to the one shown in the app.
3)Make sure you are making a POST request to http://your-ip/upload
4) Error

### Expected behavior

If you run the same script on GUI OpenSpeedTest -Server (Electron Apps)
Upload finishes without issue. 

### Logs/tracebacks

```python-traceback
`
Traceback (most recent call last):
  File "r.py", line 35, in <module>
    asyncio.run(main())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "r.py", line 32, in main
    await asyncio.gather(*tasks)
  File "r.py", line 23, in download
    await session.post(URL, data=data_generator)
  File "/Users/goredplanet/Library/Python/3.8/lib/python/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/Users/goredplanet/Library/Python/3.8/lib/python/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/goredplanet/Library/Python/3.8/lib/python/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
````
```


### Python Version

```console
Python 3.8.9
```

### aiohttp Version

```console
Name: aiohttp
Version: 3.8.1
```

### multidict Version

```console
Name: multidict
Version: 6.0.2
```

### yarl Version

```console
Name: yarl
Version: 1.8.1
```

### OS

MacOS 12.5.1 (21G83)

### Related component

Client

### Additional context

This is a CLI-Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by martindurant** [comment]
We seem to be seeing something similar in gcsfs. Is there a remediation? Should this kind of exception be considered retriable?

**Comment by clayg** [comment]
I've seen this traceback when using aiohttp, but my use-case was 100s of tasks reading 8-100KB https responses from an object store.  My problem seemed to that my python script was slow to service the ready/readable sockets and the remote service would time out waiting to send the next chunk of a pending response and disconnect the socket to the client.

Your script didn't fail for me with the `openspeedtest/latest` latest image, but I did see a different error on python 3.10.6 when I set the `chunk_size` smaller (128-256)

```
Traceback (most recent call last):                                                                                                                                            | 0/30000000 [00:00<?, ?it/s]
  File "/home/clayg/.local/share/virtualenvs/aiohttp-sandbox-oxtDudq2/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 581, in write_bytes                        | 0/30000000 [00:00<?, ?it/s]
    await self.body.write(writer)
  File "/home/clayg/.local/share/virtualenvs/aiohttp-sandbox-oxtDudq2/lib/python3.10/site-packages/aiohttp/payload.py", line 444, in write
    await writer.write(chunk)
  File "/home/clayg/.local/share/virtualenvs/aiohttp-sandbox-oxtDudq2/lib/python3.10/site-packages/aiohttp/http_writer.py", line 116, in write
    self._write(chunk)
  File "/home/clayg/.local/share/virtualenvs/aiohttp-sandbox-oxtDudq2/lib/python3.10/site-packages/aiohttp/http_writer.py", line 76, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

...

Traceback (most recent call last):
  File "/home/clayg/Workspace/scratch/aiohttp-sandbox/scripts/bug6912.py", line 36, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/clayg/Workspace/scratch/aiohttp-sandbox/scripts/bug6912.py", line 33, in main
    await asyncio.gather(*tasks)
  File "/home/clayg/Workspace/scratch/aiohttp-sandbox/scripts/bug6912.py", line 24, in download
    await session.post(URL, data=data_generator)
  File "/home/clayg/.local/share/virtualenvs/aiohttp-sandbox-oxtDudq2/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/clayg/.local/share/virtualenvs/aiohttp-sandbox-oxtDudq2/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/clayg/.local/share/virtualenvs/aiohttp-sandbox-oxtDudq2/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno None] Can not write request body for http://127.0.0.1:3000/upload
```

I'm also worried your async-generator `chunks` doesn't ever `await` and ends up blocking the event loop.  That or you need to use the `position` param to `tqdm` (I couldn't get it to work).

I think when the asyncio event loop doesn't read from a ready socket for a long time (because there's a blocking async generator, or just lots of connections) you can see a `ENOPIPE` or `ECONNRESET` errors when the event loop finally gets around to the stale connection(s).

**Comment by openspeedtest** [comment]
To reproduce this, you need to use OpenSpeedTest-Server Android App.
If I remember correctly, when we tested this with the docker image, it was not showing the error message. Just stop sending a new request or complete the existing request. @clayg

**Comment by Dreamsorcerer** [comment]
> I'm also worried your async-generator `chunks` doesn't ever `await` and ends up blocking the event loop. That or you need to use the `position` param to `tqdm` (I couldn't get it to work).

I'm not familiar with tqdm, but it looks like that iterator is just feeding data from memory. It doesn't look like it'd block for any notable amount of time, as the request likely pulls a chunk from the iterator and then leaves the iterator alone until it's ready to send more data.

**Comment by EdLeafe** [comment]
I'm getting this exception when attempting to upload a 500MB chunk of a file to S3. The full output reads:
```
Future exception was never retrieved
future: <Future finished exception=ClientOSError(32, 'Broken pipe')>
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
```
And it's not occasional; it happens every single time.

**Comment by Dreamsorcerer** [comment]
Well, if you can dig in and figure out what is causing it, that would be great. Without code to reproduce and time to look into it, it could just be S3 breaking the connection for some reason.

**Comment by EdLeafe** [comment]
Here's the part that's erroring:
```
            try:
                data: FormData = FormData()
                async with aiofiles.open(pth, "rb") as ff:
                    await ff.seek(offset)
                    data.add_field("file", await ff.read(part_size))
                    resp = await session.put(url, data=data, headers=headers)
                content = await resp.content.read()
            ...
  ```

**Comment by EdLeafe** [comment]
I added `PYTHONASYNCIODEBUG=1` and re-ran. This is the asyncio error output:

```
Future exception was never retrieved
future: <Future finished exception=ClientOSError(32, 'Broken pipe') created at /Users/ed/.pyenv/versions/3.9-dev/lib/python3.9/asyncio/base_events.py:424>
source_traceback: Object created at (most recent call last):
  File "/Users/ed/projects/ngc-cli/ngccli/modules/resource.py", line 901, in _perform_upload
    elapsed, upload_count, upload_size, failed_count, _ = http_uploader.upload_directory(
  File "/Users/ed/projects/ngc-cli/ngccli/transfer/http_uploader.py", line 319, in upload_directory
    asyncio.run(
  File "/Users/ed/.pyenv/versions/3.9-dev/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ed/.pyenv/versions/3.9-dev/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/Users/ed/.pyenv/versions/3.9-dev/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/Users/ed/.pyenv/versions/3.9-dev/lib/python3.9/asyncio/base_events.py", line 1882, in _run_once
    handle._run()
  File "/Users/ed/.pyenv/versions/3.9-dev/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ed/.cache/virtualenvs/ngccli-hHOsXGyD-py3.9/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 583, in write_bytes
    await self.body.write(writer)
  File "/Users/ed/.cache/virtualenvs/ngccli-hHOsXGyD-py3.9/lib/python3.9/site-packages/aiohttp/multipart.py", line 903, in write
    await part.write(writer)
  File "/Users/ed/.cache/virtualenvs/ngccli-hHOsXGyD-py3.9/lib/python3.9/site-packages/aiohttp/payload.py", line 247, in write
    await writer.write(self._value)
  File "/Users/ed/.cache/virtualenvs/ngccli-hHOsXGyD-py3.9/lib/python3.9/site-packages/aiohttp/http_writer.py", line 120, in write
    await self.drain()
  File "/Users/ed/.cache/virtualenvs/ngccli-hHOsXGyD-py3.9/lib/python3.9/site-packages/aiohttp/http_writer.py", line 173, in drain
    await self._protocol._drain_helper()
  File "/Users/ed/.cache/virtualenvs/ngccli-hHOsXGyD-py3.9/lib/python3.9/site-packages/aiohttp/base_protocol.py", line 85, in _drain_helper
    waiter = self._loop.create_future()
  File "/Users/ed/.pyenv/versions/3.9-dev/lib/python3.9/asyncio/base_events.py", line 424, in create_future
    return futures.Future(loop=self)
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
```

**Comment by Dreamsorcerer** [comment]
You should probably not be using those methods if the file is really that big. See https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-uploads

Not sure if that is the actual cause of your issue or not, but I'd suggest giving it a go first.

**Comment by EdLeafe** [comment]
The large files are being sent as S3 multipart uploads, where each part is 500MB. So a straight stream reader is not going to work (I've done that with single-part uploads). So I need to be able to specify a starting offset in the file, followed by a maximum number of bytes to read. `aiofiles` seemed to be the best option for that.

**Comment by Dreamsorcerer** [comment]
The 2nd example uses aiofiles, so it still looks like you could try that easily enough, just modifying it slightly to seek.

I don't really have any better suggestions, as I don't have the time or a reproducer to investigate.

**Comment by arnavmehta7** [comment]
Still a issue :\

**Comment by arnavmehta7** [comment]
My case:
I am trying to send around 1000 requests on each thread to a API. There are total of 4 threads. My each thread session has max_connections are 2000

**Comment by vegerot** [comment]
@EdLeafe Very peculiar.  I am writing a program to benchmark an HTTP server.  This program sends hundreds of concurrent requests to the server.

When I have more than about 300 concurrent sessions, I am getting this "Broken Pipe" error.  However, when I run it with `PYTHONASYNCIODEBUG=1` I can do over a thousand requests concurrently with no problem!

For some reason `PYTHONASYNCIODEBUG=1` fixes it 😁

**Comment by Dreamsorcerer** [comment]
Is this still reproducible on 3.10.5 for anyone?
There have been several parser and multipart fixes recently.

**Comment by EdLeafe** [comment]
Sorry, I'm on a different project now and don't have a setup to test the latest version.

**Comment by olindho1** [comment]
Am experiencing this sometimes in python v3.10.15, aiohttp v3.12.15. Program being killed from `aiorun.run(..., stop_on_unhandled_errors=True)`

```
Unhandled exception; stopping loop: 'Future exception was never retrieved'
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe

The above exception was the direct cause of the following exception:

ConnectionError: Connection lost
```

:(
