### ISSUE TITLE
session.get raises ClientConnectorSSLError despite ssl=False

### ISSUE THREAD

**Issue by rbuffat** [fafhrd91/aiohttp#7018]
### Describe the bug

I expected that aiohttp behaves similarly to requests `verify=False` in the respect that all SSL validation is ignored. However, for the following server still a ClientConnectorSSLError error is raised.

aiohttp documentations mentions for`ssl=False`:

> By default aiohttp uses strict checks for HTTPS protocol. Certification checks can be relaxed by setting ssl to False:

This could invalidate my assumption about ssl=False ignoring all SSL-related errors.

### To Reproduce

```
import asyncio
import aiohttp
from aiohttp import ClientSession
import requests

print(f"aiohttp version: {aiohttp.__version__}")

url = "https://terkep.torokbalint.hu/mapproxy/service?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0"

print(f"requests.get: {requests.get(url, verify=False).status_code}")

async def test_url():
    async with ClientSession() as session:
        async with session.get(url=url, ssl=False) as response:
            print(response.status)

asyncio.run(test_url())
```

### Expected behavior

No SSL error is raised

### Logs/tracebacks

```python-traceback
aiohttp version: 3.8.3
/usr/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'terkep.torokbalint.hu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
requests.get: 200
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1092, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1122, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rene/dev/aiohttp_bug/bug.py", line 17, in <module>
    asyncio.run(test_url())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/rene/dev/aiohttp_bug/bug.py", line 14, in test_url
    async with session.get(url=url, ssl=False) as response:
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 984, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host terkep.torokbalint.hu:443 ssl:False [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)]
```
```


### Python Version

```console
$ python --version
Python 3.10.8
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /usr/lib/python3.10/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by: aiobotocore, nextcord
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib/python3.10/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib/python3.10/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Arch Linux

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Documentation says it relaxes the settings (e.g. by not checking if it has a valid CA certificate).

This site seems to have screwed their security, so their server only works with a single, weak cipher:
https://www.ssllabs.com/ssltest/analyze.html?d=terkep.torokbalint.hu

If you want to weaken security even further, you need to provide a custom `SSLContext`. For example, this will allow pretty much all ciphers and provide almost no security guarantees at all:
```
    sslcontext = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    sslcontext.check_hostname = False
    sslcontext.verify_mode = ssl.CERT_NONE
    sslcontext.set_ciphers("ALL")
```

**Comment by rbuffat** [comment]
Thanks, @Dreamsorcerer! This explains it!

Our use case is a bit special. The [editor-layer-index](https://github.com/osmlab/editor-layer-index) project maintains a list of imagery services that can be used for Openstreetmap. We use aiohttp to check if these services are still alive and behaving the same. As we can't control these servers we try to ignore SSL issues as best we can. Unfortunately,  there seems to be a surprising amount of servers with such issues.

If you think this is of interest, I could create a PR that amends the documentation of aiohttp with your solution.

**Comment by Dreamsorcerer** [comment]
If there's nothing in the docs that hint about using a custom SSLContext for this, then feel free to make a PR to add it in.

If you really want to throw away everything in this case, you might want to look through the various options to see if there are any other security restrictions that can be lifted. To allow literally all ciphers, I think you'd need `"ALL:eNULL"` for the cipher list (check the openssl docs), though whether there are actually any servers in the wild that require a cipher in the eNULL category is a separate question (I'm sure a browser wouldn't connect to them atleast).
