### ISSUE TITLE
charset-normalizer 3.0.0-1 incompatibility

### ISSUE THREAD

**Issue by na-tt** [fafhrd91/aiohttp#7050]
### Describe the bug

Hi, i'm on an arch based distro (garuda) and got python-aiohttp 3.8.3-1 and python-aiohttp-cors 0.7.0-7 installed as dependencies for gns3, upon launching gns3 i get the error message included in the Logs/tracebacks section.

As i understood aiohttp has a check in place so that charset-normalizer must be of version number greater than or equal than 2.0 and less than 3.0, however the 24th of october charset-normalizer got updated to 3.0.0-1 on the arch repository causing aiohttp to break.

Meanwhile i have downgraded back to version 2.1.1-1 solving my problem but i thought i ought to let you know.

### To Reproduce

on an arch based distro, install:

- gns3-gui 2.2.34-2
- gns3-server 2.2.34-2

launch gns3

### Expected behavior

i expect aiohttp to work with python-charset-normalizer 3.0.0-1

### Logs/tracebacks

```python-traceback
Log from gns3:

> Local server process has stopped
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 800, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (charset-normalizer 3.0.0 (/usr/lib/python3.10/site-packages), Requirement.parse('charset-normalizer<3.0,>=2.0'), {'aiohttp'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/gns3server", line 33, in <module>
>     sys.exit(load_entry_point('gns3-server==2.2.34', 'console_scripts', 'gns3server')())
>   File "/usr/bin/gns3server", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/usr/lib/python3.10/site-packages/gns3server/main.py", line 29, in <module>
>     import gns3server.utils.get_resource
>   File "/usr/lib/python3.10/site-packages/gns3server/utils/get_resource.py", line 19, in <module>
>     import pkg_resources
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
>     def _initialize_master_working_set():
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'charset-normalizer<3.0,>=2.0' distribution was not found and is required by aiohttp
>
```

### Python Version

```console
$ python --version
Python 3.10.8
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: /usr/lib/python3.10/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by: aiohttp-cors, gns3-server
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib/python3.10/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib/python3.10/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Garuda Linux x86_64

### Related component

Server, Client

### Additional context

In related component i marked both since i don't really know which component gns3 is using.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
@Ousret Think there are any changes we need, or can we just raise the version requirement?

**Comment by Ousret** [comment]
There is nothing to change. Raising the upper bound version is fine.

**Comment by Ousret** [comment]
@Dreamsorcerer do you intend to push a 3.8x minor (incl dep bump) or the next scheduled is 3.9x ?

**Comment by Dreamsorcerer** [comment]
Think the plan is to go to 3.9.
