### ISSUE TITLE
can  not conect to some page youtube

### ISSUE THREAD

**Issue by thedtvn** [fafhrd91/aiohttp#7136]
### Describe the bug

get timeout on connecting  but can get page if use curl or node js 

### To Reproduce

install affter reinstall os 
then got that
`pip install aiohttp`

### Expected behavior

can req

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in main
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/helpers.py", line 720, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

### Python Version

```console
$ python --version
Python 3.8.10
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: None
Author-email: None
License: Apache 2
Location: /home/pi/.local/lib/python3.8/site-packages
Requires: yarl, attrs, async-timeout, frozenlist, aiosignal, charset-normalizer, multidict
Required-by: zingmp3py, statcord.py, soundcloud-lib, discord.py, chiasenhac.py
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.3
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/pi/.local/lib/python3.8/site-packages
Requires:
Required-by: yarl, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/pi/.local/lib/python3.8/site-packages
Requires: multidict, idna
Required-by: aiohttp
```

### OS

ubtuntu server 20.04.5 LTS (GNU/Linux 5.4.0-1077-raspi aarch64) for raspberry pi

### Related component

Client

### Additional context

![image](https://user-images.githubusercontent.com/80153297/208601623-169daa7c-8be6-4bfd-909c-8c604f827317.png)
aiohttp test code 
![image](https://user-images.githubusercontent.com/80153297/208601803-0ed77b71-ecf8-4e59-9588-603b65b90207.png)

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by thedtvn** [comment]
* update it has gon no reson
