### ISSUE TITLE
'Int or String expected' raised when passing ssl_context to TCPSite()

### ISSUE THREAD

**Issue by shaohme** [fafhrd91/aiohttp#7163]
### Describe the bug

When passing a ssl_context to TCPSite() the error below is raised.

The 'line 108' mentioined in the stack trace points to the 'await site.start()' in the code snippet below

### To Reproduce

```python
    apprunner = web.AppRunner(app)
    await apprunner.setup()

    cert_file = tempfile.NamedTemporaryFile(mode="w+b")
    key_file = tempfile.NamedTemporaryFile(mode="w+b")

    key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend(),
    )

    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, HOSTNAME)])

    alt_names = [x509.DNSName(HOSTNAME)]

    san = x509.SubjectAlternativeName(alt_names)
    # path_len=0 means this cert can only sign itself, not other certs.
    basic_contraints = x509.BasicConstraints(ca=True, path_length=0)
    now = datetime.utcnow()
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(1000)
        .not_valid_before(now)
        .not_valid_after(now + timedelta(days=10 * 365))
        .add_extension(basic_contraints, False)
        .add_extension(san, False)
        .sign(key, hashes.SHA256(), default_backend())
    )
    cert_pem = cert.public_bytes(encoding=serialization.Encoding.PEM)
    cert_file.write(cert_pem)
    cert_file.flush()


    key_pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    )
    key_file.write(key_pem)
    key_file.flush()

    ssl_ctx = ssl.create_default_context(
        purpose=ssl.Purpose.SERVER_AUTH, cafile=cert_file.name
    )
    ssl_ctx.load_cert_chain(cert_file.name, key_file.name)
    site = web.TCPSite(
        apprunner, host=HOSTNAME, port=listen_port, ssl_context=ssl_ctx
    )

    await site.start()
```

### Expected behavior

I would expect it just to use the ssl_context

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.10/threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "test_it_long.py", line 127, in run_web_srvs
      loop.run_until_complete(start_web(app, kill_q, port_q, listen_port, sslctx))
    File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
      return future.result()
    File "test_it_long.py", line 108, in start_web
      await site.start()
    File "/usr/lib/python3/dist-packages/aiohttp/web_runner.py", line 121, in start
      self._server = await loop.create_server(
    File "/usr/lib/python3.10/asyncio/base_events.py", line 1479, in create_server
      infos = await tasks.gather(*fs)
    File "/usr/lib/python3.10/asyncio/base_events.py", line 1416, in _create_server_getaddrinfo
      infos = await self._ensure_resolved((host, port), family=family,
    File "/usr/lib/python3.10/asyncio/base_events.py", line 1412, in _ensure_resolved
      return await loop.getaddrinfo(host, port, family=family, type=type,
    File "/usr/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
      return await self.run_in_executor(
    File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
      result = self.fn(*self.args, **self.kwargs)
    File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  OSError: Int or String expected
```

### Python Version

```console
3.10.9
```

### aiohttp Version

```console
3.8.3
```

### multidict Version

```console
6.0.4
```

### yarl Version

```console
1.8.1
```

### OS

Devuan testing

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> I would expect it just to use the ssl_context

It does: https://github.com/aio-libs/aiohttp/blob/3.8/aiohttp/web_runner.py#L125

**Comment by Dreamsorcerer** [comment]
Your example is incomplete, at the moment I'm expecting that `HOSTNAME` or `listen_port` are not str/int or some similar mistake.

**Comment by shaohme** [comment]
Oh damn, I found it. listen_port was accidentally set to '1'.

Sorry
