### ISSUE TITLE
OverflowError: Python int too large to convert to C ssize_t when serving a 10GiB file

### ISSUE THREAD

**Issue by paroga** [fafhrd91/aiohttp#7263]
### Describe the bug

When serving a static file with _10912798008 bytes_ an `OverflowError` is thrown. It looks to me that the limit of a 32bit integer is reached.

With `AIOHTTP_NOSENDFILE=1` the file is served as expected.

### To Reproduce

Use the following `Dockerfile` and `app.py` and access an file with _10912798008 bytes_ via HTTP.

```Dockerfile
# Dockerfile

FROM alpine:edge

RUN apk add py3-aiohttp py3-pip

ADD app.py .

CMD ["python", "app.py"]
```

```python
# app.py

from aiohttp import web

app = web.Application()
app.add_routes([web.static("/static", "/work/static")])

if __name__ == "__main__":
    web.run_app(app)
```

### Expected behavior

No exception. :wink: 

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 512, in start
    resp, reset = await task
                  ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 458, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 611, in finish_response
    await prepare_meth(request)
  File "/usr/lib/python3.11/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
    return await self._sendfile(request, fobj, offset, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1185, in sendfile
    return await self._sendfile_native(transport, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 725, in _sendfile_native
    return await self.sock_sendfile(transp._sock, file, offset, count,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 881, in sock_sendfile
    return await self._sock_sendfile_native(sock, file,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 373, in _sock_sendfile_native
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 395, in _sock_sendfile_native_impl
    sent = os.sendfile(fd, fileno, offset, blocksize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python int too large to convert to C ssize_t
```

### Python Version

```console
$ python --version
Python 3.11.3
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.4
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /usr/lib/python3.11/site-packages
Requires: aiosignal, async_timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/lib/python3.11/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /usr/lib/python3.11/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

```console
$ uname -a
Linux 64fea89ba9a5 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 Linux
```

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Well, it seems to me that you've already found the solution that the documentation recommends:

> In some situations it might be necessary to avoid using the sendfile system call even if the platform supports it. This can be accomplished by by setting environment variable AIOHTTP_NOSENDFILE=1.
https://docs.aiohttp.org/en/stable/web_reference.html?highlight=nosendfile#aiohttp.web.UrlDispatcher.add_static

If you want os.sendfile() to work with a larger int size, then you'd need to file a bug with cpython.
Not sure there's anything for us to do here.

**Comment by paroga** [comment]
I don't think that cpython can do much here, since `sizeof(size_t)` is only `4` on this platform :disappointed:.
IMHO `aiohttp` would need to send files in chunks of 2GiB on 32bit architectures.
Or maybe fallback to the current "sendfile-fallback" for large files, so that small files could still take advantage of `sendfile`.

**Comment by Dreamsorcerer** [comment]
Perhaps, but as the warning says, we only expect to be using `add_static()` in development (and the vast majority of devices are 64 bit these days anyway). So, this seems like something nobody here is going to put any time into.

If you'd like to create a PR to give that a go though, then feel free.
