### ISSUE TITLE
aiohttp request cancels the current task when raising a TimeoutError, leads to incompatibility with asyncio.timeout

### ISSUE THREAD

**Issue by arrmansa** [fafhrd91/aiohttp#7479]
### Describe the bug

When aiohttp times out, the current task's cancel counter is incremented. 
This is unexpected behaviour and should not happen.
It causes issues with asyncio.timeout
Minimum reproducible example

### code
```python
import asyncio
import aiohttp


async def minimum_error():
    current_task = asyncio.tasks.current_task()
    client = aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=1.0))
    print(current_task.cancelling())
    try:
        resp = await client.get("http://httpbin.org/delay/10")
        print(await resp.text())
    except TimeoutError:
        print("AIOHTTP TIMED OUT")
    print(current_task.cancelling())
    await client.close()

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(minimum_error())
```

### output
```bash
0
AIOHTTP TIMED OUT
1
```

### To Reproduce

# The error

1. Run the following code 
```python
import asyncio
from functools import wraps

import aiohttp


async def demonstrate_error():
    try:
        # PRINT WHEN .cancel is called for the current taks
        current_task = asyncio.tasks.current_task()
        assert current_task is not None
        old_cancel = current_task.cancel
        @wraps(old_cancel)
        def new_cancel(*args, **kwargs):
            print("CANCELING CURRENT TASK")
            return old_cancel(*args, **kwargs)
        current_task.cancel = new_cancel

        print("CREATING_CLIENT")
        client = aiohttp.ClientSession(connector=aiohttp.TCPConnector(limit=100), timeout=aiohttp.ClientTimeout(total=1.0))
        print("CREATED_CLIENT")

        # Actual issue
        async with asyncio.timeout(2) as timeout_context:
            try:
                resp = await client.get("http://httpbin.org/delay/10")  # asyncio.shield(client.get("http://httpbin.org/delay/10"))
                print(await resp.text())
            except TimeoutError:
                # current_task.uncancel()
                print("AIOHTTP TIMED OUT")
            print("CLOSING CLIENT")
            await client.close()
            print("STARTED SLEEP")
            await asyncio.sleep(99999)
            print("ENDED SLEEP")
    except TimeoutError:
        print("NORMAL TIMEOUT")
    except asyncio.exceptions.CancelledError:
        print("SOMETHING WENT VERY WRONG")
    print("State", timeout_context._state, "Initial cancels" ,timeout_context._cancelling, "Total Cancels", 1 + current_task.cancelling())  # type: ignore # uncancel in asyncio/timeouts.py:Timeout.__aexit__:108 decrements cancels by one

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(demonstrate_error())
```

Output should be 
```bash
CREATING_CLIENT
CREATED_CLIENT
CANCELING CURRENT TASK
AIOHTTP TIMED OUT
CLOSING CLIENT
STARTED SLEEP
CANCELING CURRENT TASK
SOMETHING WENT VERY WRONG
State _State.EXPIRED Initial cancels 0 Total Cancels 2
```

# 2. The fix (maybe)

On uncommenting either `current_task.uncancel()` or `asyncio.shield`, the code outputs 

```bash
CREATING_CLIENT
CREATED_CLIENT
AIOHTTP TIMED OUT
CLOSING CLIENT
STARTED SLEEP
CANCELING CURRENT TASK
NORMAL TIMEOUT
State _State.EXPIRED Initial cancels 0 Total Cancels 1
```

### Expected behavior

The current task's cancel counter should remain unchanged after a timeout error.
`asyncio.shield` and `task.uncancel()` should not be needed

### Logs/tracebacks

```python-traceback
code


import asyncio
import aiohttp
import traceback


async def minimum_error():
    current_task = asyncio.tasks.current_task()
    client = aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=1.0))
    print(current_task.cancelling())
    try:
        resp = await client.get("http://httpbin.org/delay/10")
        print(await resp.text())
    except TimeoutError as e:
        traceback.print_exception(e)
        print("AIOHTTP TIMED OUT")
    print(current_task.cancelling())
    await client.close()

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(minimum_error())


output

```bash
0
Traceback (most recent call last):
  File "/Users/arrmansa99/Documents/aiohttp_cancel_test.py", line 11, in minimum_error
    resp = await client.get("http://httpbin.org/delay/10")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/test_env/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/opt/miniconda3/envs/test_env/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/opt/miniconda3/envs/test_env/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
AIOHTTP TIMED OUT
1
```
```


### Python Version

```console
$ python --version

Python 3.11.4
```

### aiohttp Version

```console
$ python -m pip show aiohttp

Name: aiohttp
Version: 3.8.5
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /opt/miniconda3/envs/test_env/lib/python3.11/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict

Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /opt/miniconda3/envs/test_env/lib/python3.11/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl

Name: yarl
Version: 1.9.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /opt/miniconda3/envs/test_env/lib/python3.11/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

macOS
$ sw_vers
ProductName:            macOS
ProductVersion:         13.3.1
BuildVersion:           22E261

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Timeout here just uses async-timeout, which is what asyncio.timeout() is based on. If you could write a test for async-timeout (in a PR ideally), then we can look at fixing it and ensuring that they are compatible.

**Comment by Dreamsorcerer** [comment]
Actually, probably fixed by https://github.com/aio-libs/async-timeout/pull/363

**Comment by Dreamsorcerer** [comment]
Please retest with latest async-timeout.
