### ISSUE TITLE
Aiohttp ClientError: ClientOSError

### ISSUE THREAD

**Issue by shaprinskiy** [fafhrd91/aiohttp#7528]
### Describe the bug

Hi,

Problem - logging stopped due to a timeout during operation of Aiohttp (called from pyTelegramBotAPI  v.4.12.0)

### To Reproduce

1. Implemented in telegram bot with pyTelegramBotAPI  v.4.12.0
2. Reproduces when telegram bot request timeout
3. After bag the logging did stopped

### Expected behavior

After bag the logging did not stopped

### Logs/tracebacks

```python-traceback
Aug 15 18:13:15 cloudvps python3.9[672369]: 2023.Aug.15 18:13:15 ERROR TeleBot Aiohttp ClientError: ClientOSError
Aug 15 18:13:15 cloudvps python3.9[672369]: 2023.Aug.15 18:13:15 ERROR TeleBot Request timeout. Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x7f54d417d370> files=None request_timeout=360
Aug 15 18:49:50 cloudvps python3.9[672369]: 2023.Aug.15 18:49:50 ERROR TeleBot Aiohttp ClientError: ClientOSError
Aug 15 18:49:50 cloudvps python3.9[672369]: 2023.Aug.15 18:49:50 ERROR TeleBot Request timeout. Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x7f54da944040> files=None request_timeout=360
Aug 16 08:18:07 cloudvps python3.9[672369]: 2023.Aug.16 08:18:07 ERROR TeleBot Aiohttp ClientError: ClientOSError
Aug 16 08:18:07 cloudvps python3.9[672369]: --- Logging error ---
Aug 16 08:18:07 cloudvps python3.9[672369]: Traceback (most recent call last):
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/telebot/asyncio_helper.py", line 91, in _process_request
Aug 16 08:18:07 cloudvps python3.9[672369]:     async with session.request(method=method, url=API_URL.format(token, url), data=params, timeout=timeout, proxy=proxy) as resp:
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
Aug 16 08:18:07 cloudvps python3.9[672369]:     self._resp = await self._coro
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
Aug 16 08:18:07 cloudvps python3.9[672369]:     await resp.start(conn)
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
Aug 16 08:18:07 cloudvps python3.9[672369]:     message, payload = await protocol.read()  # type: ignore[union-attr]
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
Aug 16 08:18:07 cloudvps python3.9[672369]:     await self._waiter
Aug 16 08:18:07 cloudvps python3.9[672369]: aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
Aug 16 08:18:07 cloudvps python3.9[672369]: During handling of the above exception, another exception occurred:
Aug 16 08:18:07 cloudvps python3.9[672369]: Traceback (most recent call last):
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/usr/lib/python3.9/logging/handlers.py", line 74, in emit
Aug 16 08:18:07 cloudvps python3.9[672369]:     self.doRollover()
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/usr/lib/python3.9/logging/handlers.py", line 404, in doRollover
Aug 16 08:18:07 cloudvps python3.9[672369]:     if self.backupCount > 0:
Aug 16 08:18:07 cloudvps python3.9[672369]: TypeError: '>' not supported between instances of 'str' and 'int'
Aug 16 08:18:07 cloudvps python3.9[672369]: Call stack:
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/telebot/asyncio_helper.py", line 250, in get_updates
Aug 16 08:18:07 cloudvps python3.9[672369]:     return await _process_request(token, method_name, params=params, request_timeout=request_timeout)
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/telebot/asyncio_helper.py", line 101, in _process_request
Aug 16 08:18:07 cloudvps python3.9[672369]:     logger.error('Aiohttp ClientError: {0}'.format(e.__class__.__name__))
Aug 16 08:18:07 cloudvps python3.9[672369]: Message: 'Aiohttp ClientError: ClientOSError'
Aug 16 08:18:07 cloudvps python3.9[672369]: Arguments: ()
Aug 16 08:18:07 cloudvps python3.9[672369]: 2023.Aug.16 08:18:07 ERROR TeleBot Request timeout. Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x7f54d404f430> files=None request_timeout=360
Aug 16 08:18:07 cloudvps python3.9[672369]: --- Logging error ---
Aug 16 08:18:07 cloudvps python3.9[672369]: Traceback (most recent call last):
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/telebot/async_telebot.py", line 407, in _process_polling
Aug 16 08:18:07 cloudvps python3.9[672369]:     updates = await self.get_updates(offset=self.offset, allowed_updates=allowed_updates, timeout=timeout, request_timeout=request_timeout)
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/telebot/async_telebot.py", line 218, in get_updates
Aug 16 08:18:07 cloudvps python3.9[672369]:     json_updates = await asyncio_helper.get_updates(self.token, offset, limit, timeout, allowed_updates, request_timeout)
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/telebot/asyncio_helper.py", line 250, in get_updates
Aug 16 08:18:07 cloudvps python3.9[672369]:     return await _process_request(token, method_name, params=params, request_timeout=request_timeout)
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/telebot/asyncio_helper.py", line 105, in _process_request
Aug 16 08:18:07 cloudvps python3.9[672369]:     raise RequestTimeout("Request timeout. Request: method={0} url={1} params={2} files={3} request_timeout={4}".format(method, url, params, files, request_timeout, current_try))
Aug 16 08:18:07 cloudvps python3.9[672369]: telebot.asyncio_helper.RequestTimeout: Request timeout. Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x7f54d404f430> files=None request_timeout=360
Aug 16 08:18:07 cloudvps python3.9[672369]: During handling of the above exception, another exception occurred:
Aug 16 08:18:07 cloudvps python3.9[672369]: Traceback (most recent call last):
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/usr/lib/python3.9/logging/handlers.py", line 74, in emit
Aug 16 08:18:07 cloudvps python3.9[672369]:     self.doRollover()
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/usr/lib/python3.9/logging/handlers.py", line 404, in doRollover
Aug 16 08:18:07 cloudvps python3.9[672369]:     if self.backupCount > 0:
Aug 16 08:18:07 cloudvps python3.9[672369]: TypeError: '>' not supported between instances of 'str' and 'int'
Aug 16 08:18:07 cloudvps python3.9[672369]: Call stack:
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/telebot/async_telebot.py", line 306, in polling
Aug 16 08:18:07 cloudvps python3.9[672369]:     await self._process_polling(non_stop, interval, timeout, request_timeout, allowed_updates)
Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/home/user/bot_moonlanding/venv/lib/python3.9/site-packages/telebot/async_telebot.py", line 418, in _process_polling
Aug 16 08:18:07 cloudvps python3.9[672369]:     logger.error(str(e))
Aug 16 08:18:07 cloudvps python3.9[672369]: Message: 'Request timeout. Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x7f54d404f430> files=None request_timeout=360'
Aug 16 08:18:07 cloudvps python3.9[672369]: Arguments: ()
```

### Python Version

```console
Python 3.9.5
```

### aiohttp Version

```console
Name: aiohttp
Version: 3.8.4
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: /home/user/bot_moonlanding/venv/lib/python3.9/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/user/bot_moonlanding/venv/lib/python3.9/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
Name: yarl
Version: 1.9.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /home/user/bot_moonlanding/venv/lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Linux 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Unless you can create a reproducer with aiohttp alone, I don't think this has anything to do with us.

> ```
> Aug 16 08:18:07 cloudvps python3.9[672369]: Traceback (most recent call last):
> Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/usr/lib/python3.9/logging/handlers.py", line 74, in emit
> Aug 16 08:18:07 cloudvps python3.9[672369]:     self.doRollover()
> Aug 16 08:18:07 cloudvps python3.9[672369]:   File "/usr/lib/python3.9/logging/handlers.py", line 404, in doRollover
> Aug 16 08:18:07 cloudvps python3.9[672369]:     if self.backupCount > 0:
> Aug 16 08:18:07 cloudvps python3.9[672369]: TypeError: '>' not supported between instances of 'str' and 'int'
> ```

This exception is happening in the logging handling, which is obviously why your logging breaks. So, figure out how to fix this exception and your logging won't keep breaking.

> ```
> Aug 16 08:18:07 cloudvps python3.9[672369]:     logger.error(str(e))
> ```

On a side point, you should use something like `logger.exception("Exception occurred")`, not `logger.error(str(e))`.
