### ISSUE TITLE
Timeout Context Manager should be used inside a task

### ISSUE THREAD

**Issue by Cosmicoppai** [fafhrd91/aiohttp#7542]
### Describe the bug

Unable to make GET Request

### To Reproduce

```python
import asyncio
from abc import ABC, abstractmethod
import aiohttp
from typing import Dict, List, Any


def get_headers(extra: Dict[str, Any] = {}) -> Dict[str, str]:
    headers = {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "accept-language": "en-GB,en;q=0.9,ja-JP;q=0.8,ja;q=0.7,en-US;q=0.6",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36",
    }
    for key, val in extra.items():
        headers[key] = val
    return headers


class Scraper(ABC):
    session: aiohttp.ClientSession = None

    def __init__(self):
        if not self.session:
            self.session = asyncio.get_event_loop().run_until_complete(self.get_session())

    @classmethod
    async def get_session(cls):
        cls.session = aiohttp.ClientSession()
        return cls.session

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc_value, traceback):
        if self.session:
            await self.session.close()


class Animepahe(Scraper):
    _SITE_NAME: str = "animepahe"
    site_url: str = "https://animepahe.ru"
    api_url: str = "https://animepahe.ru/api"
    manifest_header = get_headers({"referer": "https://kwik.cx", "origin": "https://kwik.cx"})

    async def get_api(self, data: dict, headers: dict = get_headers()) -> dict:
        resp = await self.get(self.api_url, data, headers)
        return await resp.json()

    async def get(self, url: str, data=None, headers: dict = get_headers()) -> aiohttp.ClientResponse:
        data = {} or data
        err, tries = None, 0

        while tries < 10:
            try:
                async with self.session.get(url=url, params=data, headers=headers) as resp:
                    if resp.status != 200:
                        err = f"request failed with status: {resp.status}\n err msg: {resp.content}"
                        logging.error(f"{err}\nRetrying...")
                        raise aiohttp.ClientResponseError(None, None, message=err)

                    return resp
            except (aiohttp.ClientOSError, asyncio.TimeoutError, aiohttp.ServerDisconnectedError, aiohttp.ServerTimeoutError):
                await asyncio.sleep(choice([5, 4, 3, 2, 1]))  # randomly await
                tries += 1
                continue

        raise aiohttp.ClientResponseError(None, None, message=err)


if __name__ == "__main__":
    Scraper()

    async def main():
        scraper = Animepahe()
        print(await scraper.get_api({"m": "search", "q": "attack"}))

    asyncio.run(main())
```

### Expected behavior

JSON Response

### Logs/tracebacks

```python-traceback
T:\_lisa\env\Scripts\python.exe T:/_lisa/backend/test.py
T:\_lisa\backend\test.py:23: DeprecationWarning: There is no current event loop
  self.session = asyncio.get_event_loop().run_until_complete(self.get_session())
Traceback (most recent call last):
  File "T:\_lisa\backend\test.py", line 76, in <module>
    asyncio.run(main())
  File "C:\Users\KANAK\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\KANAK\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "T:\_lisa\backend\test.py", line 74, in main
    print(await scraper.get_api({"m": "search", "q": "attack"}))
  File "T:\_lisa\backend\test.py", line 45, in get_api
    resp = await self.get(self.api_url, data, headers)
  File "T:\_lisa\backend\test.py", line 54, in get
    async with self.session.get(url=url, params=data, headers=headers) as resp:
  File "T:\_lisa\env\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "T:\_lisa\env\lib\site-packages\aiohttp\client.py", line 467, in _request
    with timer:
  File "T:\_lisa\env\lib\site-packages\aiohttp\helpers.py", line 701, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001A508B44670>

プロセスは終了コード 1 で終了しました
```

### Python Version

```console
$ python --version
3.10.2
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.5
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: t:\_lisa\env\lib\site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: t:\_lisa\env\lib\site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: t:\_lisa\env\lib\site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Windows 10

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Your code is badly broken, you need to run everything inside the event loop (i.e. all async-related code inside of the `asyncio.run()` call).

e.g. `Scraper()` should be initialised inside `main()`, and you should not be using the low-level APIs (like `.run_until_complete()`).

**Comment by Cosmicoppai** [comment]
@Dreamsorcerer What are the differences between running an asynchronous function inside a loop within the Scraper class and initializing an instance of the Scraper class inside the main method?
Cuz, in both cases I'm trying to tweak the class var.

**Comment by Dreamsorcerer** [comment]
A lot. For example, the asyncio primitives used are tied to the event loop. You've created a ClientSession in one event loop, and then you try to access it while running in a different event loop.

So, please consider `asyncio.run()` to be the entry point of your application, and don't use the low-level asyncio APIs. If you do that, you won't have issues.
