### ISSUE TITLE
finish_response() handles only ConnectionError, not ConnectionResetError

### ISSUE THREAD

**Issue by socketpair** [fafhrd91/aiohttp#7590]
### Describe the bug

Traceback happens with streaming responses when browser closes connection.

### To Reproduce

I don't know exactly, sometimes happen. possibly when browser closes connection at inappropriate time. Possibly the difference in the way how to close - i.e. TCP FIN  or TCP RST.

### Expected behavior

No traceback.

### Logs/tracebacks

```python-traceback
Error handling request
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^

...

  File "/usr/lib64/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 954, in _iter
    resp = await method()
           ^^^^^^^^^^^^^^

....

    await response.prepare(request)
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/lib64/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/lib64/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

### Python Version

```console
Python 3.10.10
```

### aiohttp Version

```console
aiohttp-3.8.4
```

### multidict Version

```console
multidict-5.1.0
```

### yarl Version

```console
yarl-1.7.2
```

### OS

Fedora 36

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by socketpair** [comment]
https://github.com/aio-libs/aiohttp/blob/9c932f71ec5a450954cee92ff9450974414ac1d8/aiohttp/web_protocol.py#L645

I think, we just need to add `ConnectionResetError` here.

**Comment by Dreamsorcerer** [comment]
It's a subclass, so I don't think that's the problem:
https://docs.python.org/3/library/exceptions.html#ConnectionResetError

**Comment by socketpair** [comment]
Yes, you are right
