### ISSUE TITLE
Cannot make request behind a plain http proxy, aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host xxx ssl:default [None]

### ISSUE THREAD

**Issue by BreathBlush** [fafhrd91/aiohttp#8469]
### Describe the bug

Every time I want to make a request behind a plain http proxy, It fails, raised the exception: 
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.python.org:443 ssl:default [None]

![1_exception](https://github.com/aio-libs/aiohttp/assets/10967857/f2279ef8-42dc-4208-bc8c-6eafcb599231)

The proxy server has no problem cause I have tested it with requests and selenium and so many other programs....

![2_req_ok](https://github.com/aio-libs/aiohttp/assets/10967857/2e20b387-b38a-468a-b2c9-a527b5c81a0c)

If I remove `proxy` argument, It works as expected:

![3_aiook_without_proxy](https://github.com/aio-libs/aiohttp/assets/10967857/c85ad015-181c-4c79-8310-e2c118392bcc)

I have searched a lot and tried a lot included following steps
1. set `HTTP_PROXY` or `HTTPS_PROXY` in environmental variable, and set `trust_env = True` to `ClientSession`. 
2. change event loop policy by `set_event_loop_policy`
3. set `ssl=False` to `session.get` method
4. create a self-defined `sslcontext` and pass it to `session.get` method
5. update the aiohttp lib to latest version `3.9.5`
6. switch to different platform: `Windows 10 LTSC 2021`, `Debian 12(Book Worm)`
7. swtich to different python version: `3.11` on Linux, `3.12` on Windows

Now I'm exhausted and don't know what to do.

### To Reproduce

1. setup a plain http proxy, using tools like: gost, goproxy
2. test the proxy server to ensure it works normally
3. using aiohttp make request behind that proxy server
```python
import asyncio
import aiohttp

env = 'http://192.168.2.100:10005'

async def main():
    async with aiohttp.ClientSession() as cs:
        async with cs.get("https://www.python.org", proxy=env) as r:
            res = await r.text()
            print(res[:100])

asyncio.run(main())
```
4. It raised the exception

![1_exception](https://github.com/aio-libs/aiohttp/assets/10967857/709730a0-f869-4562-a1e0-452a19ea268f)

5. remove `proxy=env` argument, it works normally.

### Expected behavior

It should return the text of the target web.

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/home/max/remote_projects/test-pro/test_aiohttp.py", line 12, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/max/remote_projects/test-pro/test_aiohttp.py", line 8, in main
    async with cs.get("https://www.python.org", proxy=env) as r:
  File "/home/max/remote_projects/test-pro/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/max/remote_projects/test-pro/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/max/remote_projects/test-pro/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/max/remote_projects/test-pro/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 942, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/max/remote_projects/test-pro/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1379, in _create_proxy_connection
    return await self._start_tls_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/max/remote_projects/test-pro/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 1172, in _start_tls_connection
    raise client_error(req.connection_key, OSError(msg))
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.python.org:443 ssl:default [None]
```

### Python Version

```console
$ python --version
Python 3.12.4 on Windows
Python 3.11.2 on Debian Bookworm
```

### aiohttp Version

```console
$ python -m pip show aiohttp

Name: aiohttp
Version: 3.9.5
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: C:\Python\312\Lib\site-packages
Requires: aiosignal, attrs, frozenlist, multidict, yarl
Required-by:

same version both on Windows and Debian
```

### multidict Version

```console
$ python -m pip show multidict

Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: C:\Python\312\Lib\site-packages
Requires:
Required-by: aiohttp, yarl

same version both on Windows and Debian
```

### yarl Version

```console
$ python -m pip show yarl

Name: yarl
Version: 1.9.4
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: C:\Python\312\Lib\site-packages
Requires: idna, multidict
Required-by: aiohttp

same version both on Windows and Debian
```

### OS

Windows 10 2021 LTSC

Debian bookworm

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by BreathBlush** [comment]
I just tested it with other program which set up http proxy and found no problem, maybe it's about the http server not aiohttp. So I decide to close this comment. Sorry about that.
