### ISSUE TITLE
ClientConnectorCertificateError / SSLCertVerificationError after update (regression)

### ISSUE THREAD

**Issue by Julian-J-S** [fafhrd91/aiohttp#9869]
### Describe the bug

Great library which gave me nice performence improvements 😎 
BUT unfortunately updating aiohttp dependency recently of a project causes ClientConnectorCertificateError / SSLCertVerificationError.

Using "requests" everything works as expected ✔️ 
```python
requests.post(
    url=URL,
    headers=HEADERS,
    json=JSON,
    },
).json()
```

Using "aiohttp" worked in the past (!) but raises now ❌ 
```python
async with aiohttp.ClientSession() as session:
    async with session.post(
        url=URL,
        headers=HEADERS,
        json=JSON,
        # ssl=False,  # <<< only works with ssl=False...
    ) as response:
        response_json = await response.json()
```

The only solution I found is `ssl=False` which is no option.
Also "requests" uses ssl by default and there is no problem.

### To Reproduce

see description.

### Expected behavior

I expect this to work like it did before.
This is a breaking change (at least for me) so this was very unexpected and problematic.

### Logs/tracebacks

```python-traceback
ClientConnectorCertificateError: Cannot connect to host <XXX>:443 ssl:True [SSLCertVerificationError: (5, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)')]
```

### Python Version

```console
$ python --version
3.13
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.11.0
```

### multidict Version

```console
$ python -m pip show multidict
I dont use "pip" but "uv"
```

### propcache Version

```console
$ python -m pip show propcache
I dont use "pip" but "uv"
```

### yarl Version

```console
$ python -m pip show yarl
I dont use "pip" but "uv"
```

### OS

Windows

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Julian-J-S** [comment]
> > unfortunately updating aiohttp dependency
> 
> Please provide version numbers.
> 
> Could maybe be related to the change to aiohappyeyeballs, but not too sure how. Otherwise, this typically indicates your certificates are not installed/accessible/up-to-date. You can use certifi (which requests uses by default) by following the docs: https://docs.aiohttp.org/en/stable/client_advanced.html#example-use-certifi

Thanks a lot for your help! 😄

 I got it working like this:
```python
async with aiohttp.ClientSession(
    connector=aiohttp.TCPConnector(ssl=ssl.create_default_context(cafile=certifi.where())),
) as session:
    ...
```

I am right now on `aiohttp=3.11.0` but cannot tell you the previous version.
However, I am 100% sure that the original code worked without additional ssl magic!

Would love to see it working again by default without this additional "overhead".

**Comment by Dreamsorcerer** [comment]
Without knowing the version, it's difficult to tell what might have changed. It could also be something else changed on your system that caused the system certificates to not be found. Or, maybe the site your connecting to has deployed a new certificate, with a CA that is not present in your system certificates. The aiohttp upgrade could just be a coincidence, so it'd need more testing to rule it out.

**Comment by bdraco** [comment]
I looked at the changes between 3.10 and 3.11 and didn't find anything related to SSL that would cause this. If I had to guess, I'd expect its due to a dependency change unless aiohttp was being upgraded from a very old version.

**Comment by oussama-gourari** [comment]
Having similar problem after upgrading to Python 3.13:
`ClientConnectorCertificateError: Cannot connect to host oauth.battle.net:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)')]`

**Comment by bdraco** [comment]
Thats likely due to the openssl version requiring the certificate to meet newest CAB forum requirements and comply with the RFC https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.9

**Comment by Dreamsorcerer** [comment]
I'm reasonably confident that PR makes no functional changes. Are you sure that the issue goes away when downgrading again to 3.10.5? If so, would you be able to do a git bisect or similar to find the exact commit (by checking out the 3.10 branch)?

**Comment by szelenka-cisco** [comment]
it doesn't make sense to me either, but here's the test we ran. It only surfaces when enabling FIPS mode

Version 3.10.5 is installed
```bash
python3 --version
Python 3.12.5
root@5604b132aa16:/app# python3 -m pip freeze | grep aiohttp
aiohttp==3.10.5
```

Simple test to enable FIPS mode and make a HTTPS request while verifying SSL certificate:
```bash
root@5604b132aa16:/app# python3 << EOF
import aiohttp
import asyncio
import ctypes

async def main():
    libcrypto = ctypes.CDLL("libcrypto.so.1.1")
    FIPS_mode = libcrypto.FIPS_mode
    FIPS_mode.argtypes = []
    FIPS_mode.restype = ctypes.c_int
    FIPS_mode_set = libcrypto.FIPS_mode_set
    FIPS_mode_set.argtypes = [ctypes.c_int]
    FIPS_mode_set.restype = ctypes.c_int
    ERR_get_error = libcrypto.ERR_get_error
    ERR_get_error.argtypes = []
    ERR_get_error.restype = ctypes.c_int
    FIPS_mode_set(1)

    connector = aiohttp.TCPConnector(verify_ssl=True)
    async with aiohttp.ClientSession(connector=connector) as session:
        async with session.get('https://github.com') as resp:
            print(resp.status)

asyncio.run(main())
EOF
200
```

Upgrade to version 3.10.6
```bash
python3 -m pip install aiohttp==3.10.6
Collecting aiohttp==3.10.6
...
root@5604b132aa16:/app# python3 -m pip freeze | grep aiohttp
aiohttp==3.10.6
```

Execute the same test in FIPS mode that worked on version 3.10.6, but now it gives the SSL error
```bash
python3 << EOF
import aiohttp
import asyncio
import ctypes

async def main():
    libcrypto = ctypes.CDLL("libcrypto.so.1.1")
    FIPS_mode = libcrypto.FIPS_mode
    FIPS_mode.argtypes = []
    FIPS_mode.restype = ctypes.c_int
    FIPS_mode_set = libcrypto.FIPS_mode_set
    FIPS_mode_set.argtypes = [ctypes.c_int]
    FIPS_mode_set.restype = ctypes.c_int
    ERR_get_error = libcrypto.ERR_get_error
    ERR_get_error.argtypes = []
    ERR_get_error.restype = ctypes.c_int
    FIPS_mode_set(1)

    connector = aiohttp.TCPConnector(verify_ssl=True)
    async with aiohttp.ClientSession(connector=connector) as session:
        async with session.get('https://github.com') as resp:
            print(resp.status)

asyncio.run(main())
EOF
Traceback (most recent call last):
  File "/opt/python/lib/python3.12/site-packages/aiohttp/connector.py", line 1068, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/asyncio/base_events.py", line 1148, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/asyncio/base_events.py", line 1181, in _create_connection_transport
    await waiter
  File "/opt/python/lib/python3.12/asyncio/sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "/opt/python/lib/python3.12/asyncio/sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "/opt/python/lib/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
  File "/opt/python/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<stdin>", line 22, in main
  File "/opt/python/lib/python3.12/site-packages/aiohttp/client.py", line 1355, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/site-packages/aiohttp/client.py", line 659, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/site-packages/aiohttp/connector.py", line 557, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/site-packages/aiohttp/connector.py", line 1002, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection
    raise last_exc
  File "/opt/python/lib/python3.12/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.12/site-packages/aiohttp/connector.py", line 1070, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1000)')]
```

Change the pattern of initializing aiohttp.TCPConnector as suggested above, and now it'll work fine
```bash
python3 << EOF
import aiohttp
import asyncio
import ctypes
import certifi
import ssl

async def main():
    libcrypto = ctypes.CDLL("libcrypto.so.1.1")
    FIPS_mode = libcrypto.FIPS_mode
    FIPS_mode.argtypes = []
    FIPS_mode.restype = ctypes.c_int
    FIPS_mode_set = libcrypto.FIPS_mode_set
    FIPS_mode_set.argtypes = [ctypes.c_int]
    FIPS_mode_set.restype = ctypes.c_int
    ERR_get_error = libcrypto.ERR_get_error
    ERR_get_error.argtypes = []
    ERR_get_error.restype = ctypes.c_int
    FIPS_mode_set(1)

    connector = aiohttp.TCPConnector(verify_ssl=True, ssl=ssl.create_default_context(cafile=certifi.where()))
    async with aiohttp.ClientSession(connector=connector) as session:
        async with session.get('https://github.com') as resp:
            print(resp.status)

asyncio.run(main())
EOF
200
```
